#pragma once
// Return kind and call behaviour of each builtin, shared by the VM and the
// native compiler. Sorted by name; lookup is a binary search over the table.
// tools/check_builtin_sigs.jdb checks the names against help.txt.

#include <cstddef>
#include <cstdint>
#include <string_view>

enum class BuiltinRet : uint8_t {
    Unknown,  // not listed
    None,     // a procedure: every path answers NONE
    F64,
    I64,
    Bool,
    Str,      // listed only for names without a trailing $
    Arr,      // flat JdbArray
    Handle,   // VM Value in the value store: maps, tensors, mixed kinds
};

enum BuiltinFlags : uint16_t {
    BF_NONE = 0,
    BF_DATE = 1,    // answers a date
    BF_NO_VEC = 2,      // takes an array argument whole instead of per element
    BF_READS_ARGS = 4,     // reads its string arguments without keeping them
    BF_FRESH_STR = 8,      // answers a newly allocated string the caller owns
    BF_KEEPS_ARGS = 16,    // stores its arguments in a container or channel
    BF_TAGGED_CELLS = 32,  // answers an array whose cells differ in kind
    BF_MAP_ARG1 = 64,      // takes a map as its first argument
    BF_CONST = 128,        // a built-in constant, not assignable
    // Answers more than one kind, and the native compiler already has an
    // answer for that: it decides the kind itself, or it refuses the call.
    // Either way the author has nothing to do, so --lint and -c stay quiet.
    BF_COMPILER_HANDLES = 256,
};

struct BuiltinSig {
    const char* name;
    BuiltinRet ret;
    uint16_t flags;
};

inline constexpr BuiltinSig kBuiltinSigs[] = {
    {"ABS", BuiltinRet::F64, BF_NONE},
    {"ACOS", BuiltinRet::F64, BF_NONE},
    {"AGG", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.ARGMAX", BuiltinRet::I64, BF_NO_VEC},
    {"AI.CHAT", BuiltinRet::Str, BF_NO_VEC},
    {"AI.CHAT_JSON", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CHAT_RAW", BuiltinRet::Str, BF_NO_VEC},
    {"AI.CHAT_STREAM", BuiltinRet::Str, BF_NO_VEC},
    {"AI.CHAT_TOKENS", BuiltinRet::I64, BF_NO_VEC},
    {"AI.CLASSIFIER_ADD", BuiltinRet::I64, BF_NO_VEC},
    {"AI.CLASSIFIER_ADD_BATCH", BuiltinRet::I64, BF_NO_VEC},
    {"AI.CLASSIFIER_BUILD_INDEX", BuiltinRet::None, BF_NO_VEC},
    {"AI.CLASSIFIER_CREATE", BuiltinRet::I64, BF_NO_VEC},
    {"AI.CLASSIFIER_FREE", BuiltinRet::None, BF_NO_VEC},
    {"AI.CLASSIFIER_INFO", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.CLASSIFIER_LOAD", BuiltinRet::I64, BF_NO_VEC},
    {"AI.CLASSIFIER_PREDICT", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.CLASSIFIER_SAVE", BuiltinRet::None, BF_NO_VEC},
    {"AI.CLEAR_GRAMMAR", BuiltinRet::None, BF_NO_VEC},
    {"AI.CLEAR_HISTORY", BuiltinRet::None, BF_NO_VEC},
    {"AI.COSINE_SIM", BuiltinRet::F64, BF_NO_VEC},
    {"AI.DETOKENIZE", BuiltinRet::Str, BF_NO_VEC},
    {"AI.EMBED", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.EMBED_LLM", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.FREE", BuiltinRet::None, BF_NO_VEC},
    {"AI.FREE_LLM", BuiltinRet::None, BF_NO_VEC},
    {"AI.GET_HISTORY", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.INFO", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.LIST", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.LLM_INFO", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.LOAD", BuiltinRet::I64, BF_NO_VEC},
    {"AI.LOAD_EMBEDDINGS", BuiltinRet::I64, BF_NO_VEC},
    {"AI.LOAD_LLM", BuiltinRet::I64, BF_NO_VEC},
    {"AI.NORMALIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.RAG_ADD", BuiltinRet::I64, BF_NO_VEC},
    {"AI.RAG_ADD_DIR", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.RAG_ADD_FILE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_BUILD_INDEX", BuiltinRet::None, BF_NO_VEC},
    {"AI.RAG_CLEAR", BuiltinRet::None, BF_NO_VEC},
    {"AI.RAG_CREATE", BuiltinRet::I64, BF_NO_VEC},
    {"AI.RAG_FREE", BuiltinRet::None, BF_NO_VEC},
    {"AI.RAG_INFO", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.RAG_LOAD", BuiltinRet::I64, BF_NO_VEC},
    {"AI.RAG_QUERY", BuiltinRet::Str, BF_NO_VEC},
    {"AI.RAG_QUERY_FULL", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.RAG_QUERY_STREAM", BuiltinRet::Str, BF_NO_VEC},
    {"AI.RAG_SAVE", BuiltinRet::None, BF_NO_VEC},
    {"AI.RAG_SEARCH", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.RUN", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.SET", BuiltinRet::None, BF_NO_VEC},
    {"AI.SET_GRAMMAR", BuiltinRet::None, BF_NO_VEC},
    {"AI.SET_JSON_MODE", BuiltinRet::None, BF_NO_VEC},
    {"AI.SIMILARITY", BuiltinRet::F64, BF_NO_VEC},
    {"AI.SOFTMAX", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TENSOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOKENIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.TOKEN_COUNT", BuiltinRet::I64, BF_NO_VEC},
    {"AI.TOOL_ADD", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOOL_CHAT", BuiltinRet::Str, BF_NO_VEC},
    {"AI.TOOL_LIST", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.TOOL_REMOVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOPK", BuiltinRet::Arr, BF_NO_VEC},
    {"ALL", BuiltinRet::I64, BF_NO_VEC},
    {"ANY", BuiltinRet::I64, BF_NO_VEC},
    {"APPEND", BuiltinRet::Arr, BF_NO_VEC | BF_KEEPS_ARGS | BF_TAGGED_CELLS},
    {"ASC", BuiltinRet::I64, BF_READS_ARGS},
    {"ASIN", BuiltinRet::F64, BF_NONE},
    {"ATAN", BuiltinRet::F64, BF_NONE},
    {"ATAN2", BuiltinRet::F64, BF_NONE},
    {"AUDIO.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.FREE", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.FREEMUS", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.INIT", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.LOADMUS", BuiltinRet::I64, BF_NO_VEC},
    {"AUDIO.LOADWAV", BuiltinRet::I64, BF_NO_VEC},
    {"AUDIO.PAUSE", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.PAUSEMUS", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.PLAY", BuiltinRet::I64, BF_NO_VEC},
    {"AUDIO.PLAYMUS", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.RESUME", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.RESUMEMUS", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.STOP", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.STOPMUS", BuiltinRet::None, BF_NO_VEC},
    {"AUDIO.VOLUME", BuiltinRet::I64, BF_NO_VEC},
    {"AUDIO.VOLUMEMUS", BuiltinRet::I64, BF_NO_VEC},
    {"AWAIT", BuiltinRet::Handle, BF_NO_VEC},
    {"BIN$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"BINREADER$", BuiltinRet::Unknown, BF_NO_VEC},
    {"BINWRITER", BuiltinRet::None, BF_NO_VEC},
    {"BYTEAT", BuiltinRet::I64, BF_READS_ARGS},
    {"CAM.BOUNDS", BuiltinRet::None, BF_NO_VEC},
    {"CAM.FOLLOW", BuiltinRet::None, BF_NO_VEC},
    {"CAM.SET", BuiltinRet::None, BF_NO_VEC},
    {"CAM.SHAKE", BuiltinRet::None, BF_NO_VEC},
    {"CAM.X", BuiltinRet::F64, BF_NO_VEC},
    {"CAM.Y", BuiltinRet::F64, BF_NO_VEC},
    {"CBOOL", BuiltinRet::Bool, BF_READS_ARGS},
    {"CD", BuiltinRet::Str, BF_NO_VEC},
    {"CDATE", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"CDBL", BuiltinRet::F64, BF_READS_ARGS},
    {"CEIL", BuiltinRet::F64, BF_NONE},
    {"CHAN.CAP", BuiltinRet::I64, BF_NO_VEC},
    {"CHAN.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"CHAN.IS_CLOSED", BuiltinRet::Bool, BF_NO_VEC},
    {"CHAN.IS_EOF", BuiltinRet::Bool, BF_NO_VEC},
    {"CHAN.IS_TIMEOUT", BuiltinRet::Bool, BF_NO_VEC},
    {"CHAN.LEN", BuiltinRet::I64, BF_NO_VEC},
    {"CHAN.OPEN", BuiltinRet::I64, BF_NO_VEC},
    {"CHAN.RECV", BuiltinRet::Handle, BF_NO_VEC},
    {"CHAN.SELECT", BuiltinRet::I64, BF_NO_VEC},
    {"CHAN.SEND", BuiltinRet::None, BF_NO_VEC | BF_KEEPS_ARGS},
    {"CHAN.TRY_RECV", BuiltinRet::Handle, BF_NO_VEC},
    {"CHR", BuiltinRet::Str, BF_FRESH_STR},
    {"CHR$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"CHUNK", BuiltinRet::Arr, BF_NO_VEC},
    {"CINT", BuiltinRet::I64, BF_READS_ARGS},
    {"CIRCLE", BuiltinRet::None, BF_NO_VEC},
    {"CIRCLE_SECTOR", BuiltinRet::None, BF_NO_VEC},
    {"CLAMP", BuiltinRet::F64, BF_NONE},
    {"CLEAR_RECUR", BuiltinRet::None, BF_NO_VEC},
    {"CLIPBOARD.GET$", BuiltinRet::Str, BF_NO_VEC},
    {"CLIPBOARD.SET", BuiltinRet::None, BF_NO_VEC},
    {"CLNG", BuiltinRet::I64, BF_READS_ARGS},
    {"CLS", BuiltinRet::None, BF_NO_VEC},
    {"CODEC.BASE64_DECODE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.BASE64_ENCODE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.CRC32", BuiltinRet::I64, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.CRC32$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.DEFLATE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.HMAC$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.INFLATE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.PBKDF2$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.RANDOMBYTES$", BuiltinRet::Unknown, BF_NO_VEC},
    {"CODEC.SHA256$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.UUID$", BuiltinRet::Unknown, BF_NO_VEC},
    {"COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"COLORDIALOG", BuiltinRet::I64, BF_NO_VEC},
    {"CONVOLVE", BuiltinRet::Arr, BF_NO_VEC},
    {"COPYV", BuiltinRet::Arr, BF_NO_VEC},
    {"COS", BuiltinRet::F64, BF_NONE},
    {"COSH", BuiltinRet::F64, BF_NONE},
    {"COUNT", BuiltinRet::I64, BF_NO_VEC},
    {"CREATEOBJECT", BuiltinRet::Handle, BF_NO_VEC},
    {"CROSS", BuiltinRet::Arr, BF_NO_VEC},
    {"CSNG", BuiltinRet::F64, BF_READS_ARGS},
    {"CSTR", BuiltinRet::Str, BF_READS_ARGS | BF_FRESH_STR},
    {"CSVHEADER", BuiltinRet::Arr, BF_NO_VEC},
    {"CSVREADER", BuiltinRet::Arr, BF_NO_VEC},
    {"CSVWRITER", BuiltinRet::None, BF_NO_VEC},
    {"CUMPROD", BuiltinRet::Arr, BF_NO_VEC},
    {"CUMSUM", BuiltinRet::Arr, BF_NO_VEC},
    {"CURSOR", BuiltinRet::None, BF_NO_VEC},
    {"CVDATE", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"DATE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"DATE.PARTS", BuiltinRet::Handle, BF_NO_VEC},
    {"DATE.UTC", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"DATEADD", BuiltinRet::Str, BF_DATE},
    {"DATEDIFF", BuiltinRet::F64, BF_READS_ARGS},
    {"DATERANGE", BuiltinRet::Arr, BF_NO_VEC},
    {"DAY", BuiltinRet::I64, BF_NONE},
    {"DEBUG.ASSERT", BuiltinRet::None, BF_NO_VEC},
    {"DEBUG.PRINT", BuiltinRet::None, BF_NO_VEC},
    {"DET", BuiltinRet::F64, BF_NO_VEC},
    {"DIFF", BuiltinRet::Arr, BF_NO_VEC},
    {"DIR", BuiltinRet::None, BF_NO_VEC},
    {"DIR$", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"DISTANCE", BuiltinRet::F64, BF_NO_VEC},
    {"DOT", BuiltinRet::F64, BF_NO_VEC},
    {"DRAWCOLOR", BuiltinRet::None, BF_NO_VEC},
    {"DROP", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"DROP_WHILE", BuiltinRet::Arr, BF_NO_VEC},
    {"DUMP", BuiltinRet::None, BF_NO_VEC},
    {"EIG", BuiltinRet::Handle, BF_NO_VEC},
    {"ELLIPSE", BuiltinRet::None, BF_NO_VEC},
    {"ENDSWITH", BuiltinRet::Bool, BF_READS_ARGS},
    {"ENUMERATE", BuiltinRet::Arr, BF_NO_VEC},
    {"EOMONTH", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"EVAL", BuiltinRet::Unknown, BF_NO_VEC},
    {"EXECUTE", BuiltinRet::None, BF_NO_VEC},
    {"EXP", BuiltinRet::F64, BF_NONE},
    {"FFT", BuiltinRet::Arr, BF_NO_VEC},
    {"FILE.AT_EOF", BuiltinRet::Bool, BF_NO_VEC},
    {"FILE.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"FILE.COPY", BuiltinRet::Bool, BF_NO_VEC},
    {"FILE.EXISTS", BuiltinRet::Bool, BF_NO_VEC},
    {"FILE.ISDIR", BuiltinRet::Bool, BF_NO_VEC},
    {"FILE.MOVE", BuiltinRet::Bool, BF_NO_VEC},
    {"FILE.OPEN_LINES", BuiltinRet::I64, BF_NO_VEC},
    {"FILE.OPEN_TAIL", BuiltinRet::I64, BF_NO_VEC},
    {"FILE.READLINE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.SIZE", BuiltinRet::I64, BF_NO_VEC},
    {"FILE.STAT", BuiltinRet::Handle, BF_NO_VEC},
    {"FILE.STREAM_LINES", BuiltinRet::I64, BF_NO_VEC},
    {"FILE.STREAM_TAIL", BuiltinRet::I64, BF_NO_VEC},
    {"FILEOPEN$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILESAVE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILLV", BuiltinRet::Arr, BF_NO_VEC},
    {"FILTER", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"FIND_IN_ARRAY", BuiltinRet::I64, BF_NO_VEC},
    {"FLATTEN", BuiltinRet::Arr, BF_NO_VEC},
    {"FLOOR", BuiltinRet::F64, BF_NONE},
    {"FONTDIALOG$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.BUTTON", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.CHECKBOX", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.CHILD", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"FORM.COMBO", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.CREATE", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.DATETIME", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.DOEVENTS", BuiltinRet::Bool, BF_NO_VEC},
    {"FORM.FIND", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.FRAME", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.GET", BuiltinRet::Handle, BF_NO_VEC},
    {"FORM.LABEL", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.LINE", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.LISTBOX", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.LISTVIEW", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.LOAD", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.MDI", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.MENU", BuiltinRet::None, BF_NO_VEC},
    {"FORM.NODE", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.PICTURE", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.POPUP", BuiltinRet::None, BF_NO_VEC},
    {"FORM.PROGRESS", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.RADIO", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.RICHTEXT", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.RUN", BuiltinRet::None, BF_NO_VEC},
    {"FORM.SET", BuiltinRet::None, BF_NO_VEC},
    {"FORM.SHAPE", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.SHOW", BuiltinRet::None, BF_NO_VEC},
    {"FORM.SLIDER", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.STATUSBAR", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.TABPAGE", BuiltinRet::None, BF_NO_VEC},
    {"FORM.TABS", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.TEXTBOX", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.TIMER", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.TOOLBAR", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.TREEVIEW", BuiltinRet::I64, BF_NO_VEC},
    {"FORM.UPDOWN", BuiltinRet::I64, BF_NO_VEC},
    {"FORMAT$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"FORMAT_DATE", BuiltinRet::Str, BF_NONE},
    {"FRMV$", BuiltinRet::Unknown, BF_NO_VEC | BF_FRESH_STR},
    {"FUNCS", BuiltinRet::None, BF_NO_VEC},
    {"FX.ADD", BuiltinRet::Bool, BF_NONE},
    {"FX.FREE", BuiltinRet::None, BF_NO_VEC},
    {"FX.MIX", BuiltinRet::Bool, BF_NONE},
    {"FX.NEW", BuiltinRet::I64, BF_NO_VEC},
    {"FX.PROCESS", BuiltinRet::Arr, BF_NO_VEC},
    {"FX.SET", BuiltinRet::Bool, BF_NONE},
    {"FX.SPLIT", BuiltinRet::Bool, BF_NONE},
    {"GCD", BuiltinRet::I64, BF_NO_VEC},
    {"GETENV$", BuiltinRet::Unknown, BF_NO_VEC},
    {"GETX", BuiltinRet::I64, BF_NO_VEC},
    {"GETY", BuiltinRet::I64, BF_NO_VEC},
    {"GFX.CAPTURE", BuiltinRet::I64, BF_NO_VEC},
    {"GFX.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"GFX.COLOR_TO_ALPHA", BuiltinRet::None, BF_NO_VEC},
    {"GFX.DELAY", BuiltinRet::None, BF_NO_VEC},
    {"GFX.DRAWIMAGE", BuiltinRet::None, BF_NO_VEC},
    {"GFX.DRAWIMAGE_EX", BuiltinRet::None, BF_NO_VEC},
    {"GFX.DRAWIMAGE_REGION", BuiltinRet::None, BF_NO_VEC},
    {"GFX.DRAW_CAPTURE", BuiltinRet::None, BF_NO_VEC},
    {"GFX.FADE", BuiltinRet::None, BF_NO_VEC},
    {"GFX.FREEIMAGE", BuiltinRet::None, BF_NO_VEC},
    {"GFX.HSV_RGB", BuiltinRet::Arr, BF_NO_VEC},
    {"GFX.KEYSTATE", BuiltinRet::Bool, BF_NO_VEC},
    {"GFX.LOADIMAGE", BuiltinRet::I64, BF_NO_VEC},
    {"GFX.MOUSEBUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"GFX.MOUSEX", BuiltinRet::I64, BF_NO_VEC},
    {"GFX.MOUSEY", BuiltinRet::I64, BF_NO_VEC},
    {"GFX.PLOT_POINTS", BuiltinRet::None, BF_NO_VEC},
    {"GFX.PLOT_POINTS_TEX", BuiltinRet::None, BF_NO_VEC},
    {"GFX.POLLEVENT", BuiltinRet::Str, BF_NO_VEC},
    {"GFX.SAVE_IMAGE", BuiltinRet::None, BF_NO_VEC},
    {"GFX.SAVE_SCREENSHOT", BuiltinRet::None, BF_NO_VEC},
    {"GFX.TEXTSIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"GFX.TICKS", BuiltinRet::I64, BF_NO_VEC},
    {"GL.ATTRIB", BuiltinRet::None, BF_NO_VEC},
    {"GL.BUFFER.DELETE", BuiltinRet::None, BF_NO_VEC},
    {"GL.CLEAR", BuiltinRet::None, BF_NO_VEC},
    {"GL.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"GL.DISABLE", BuiltinRet::None, BF_NO_VEC},
    {"GL.DRAW.LINES", BuiltinRet::None, BF_NO_VEC},
    {"GL.DRAW.TRIS", BuiltinRet::None, BF_NO_VEC},
    {"GL.DRAW.TRIS.IDX", BuiltinRet::None, BF_NO_VEC},
    {"GL.EBO", BuiltinRet::I64, BF_NO_VEC},
    {"GL.ENABLE", BuiltinRet::None, BF_NO_VEC},
    {"GL.FLIP", BuiltinRet::None, BF_NO_VEC},
    {"GL.SAVE_SCREENSHOT", BuiltinRet::None, BF_NO_VEC},
    {"GL.SHADER", BuiltinRet::I64, BF_NO_VEC},
    {"GL.SHADER.DELETE", BuiltinRet::None, BF_NO_VEC},
    {"GL.TEX.BIND", BuiltinRet::None, BF_NO_VEC},
    {"GL.TEX.DELETE", BuiltinRet::None, BF_NO_VEC},
    {"GL.TEX.LOAD", BuiltinRet::I64, BF_NO_VEC},
    {"GL.UNIFORM.F1", BuiltinRet::None, BF_NO_VEC},
    {"GL.UNIFORM.F3", BuiltinRet::None, BF_NO_VEC},
    {"GL.UNIFORM.F4", BuiltinRet::None, BF_NO_VEC},
    {"GL.UNIFORM.I1", BuiltinRet::None, BF_NO_VEC},
    {"GL.UNIFORM.MAT4", BuiltinRet::None, BF_NO_VEC},
    {"GL.USE", BuiltinRet::None, BF_NO_VEC},
    {"GL.VAO", BuiltinRet::I64, BF_NO_VEC},
    {"GL.VAO.BIND", BuiltinRet::None, BF_NO_VEC},
    {"GL.VAO.DELETE", BuiltinRet::None, BF_NO_VEC},
    {"GL.VBO", BuiltinRet::I64, BF_NO_VEC},
    {"GL.VBO.BIND", BuiltinRet::None, BF_NO_VEC},
    {"GL.VIEWPORT", BuiltinRet::None, BF_NO_VEC},
    {"GL.WINDOW", BuiltinRet::None, BF_NO_VEC},
    {"GRADE", BuiltinRet::Arr, BF_NO_VEC},
    {"GROUPBY", BuiltinRet::Handle, BF_NO_VEC | BF_COMPILER_HANDLES},
    {"GUI.AVAIL_HEIGHT", BuiltinRet::F64, BF_NO_VEC},
    {"GUI.AVAIL_WIDTH", BuiltinRet::F64, BF_NO_VEC},
    {"GUI.BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_CHILD", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_MAIN_MENU_BAR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_MENU", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_MENU_BAR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_POPUP", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_POPUP_MODAL", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_TABLE", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_TAB_BAR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_TAB_ITEM", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.CHECKBOX", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.CLOSE_CURRENT_POPUP", BuiltinRet::None, BF_NO_VEC},
    {"GUI.COL", BuiltinRet::I64, BF_NO_VEC},
    {"GUI.COLLAPSING_HEADER", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.COLOR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.COMBO", BuiltinRet::I64, BF_NO_VEC},
    {"GUI.DISPLAY_HEIGHT", BuiltinRet::F64, BF_NO_VEC},
    {"GUI.DISPLAY_WIDTH", BuiltinRet::F64, BF_NO_VEC},
    {"GUI.DUMMY", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_CHILD", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_MAIN_MENU_BAR", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_MENU", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_MENU_BAR", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_POPUP", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_TABLE", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_TAB_BAR", BuiltinRet::None, BF_NO_VEC},
    {"GUI.END_TAB_ITEM", BuiltinRet::None, BF_NO_VEC},
    {"GUI.FLAG", BuiltinRet::I64, BF_NO_VEC},
    {"GUI.HELPMARKER", BuiltinRet::None, BF_NO_VEC},
    {"GUI.IMAGE", BuiltinRet::Bool, BF_NONE},
    {"GUI.INPUT", BuiltinRet::Str, BF_NO_VEC},
    {"GUI.INPUT_DOUBLE", BuiltinRet::F64, BF_NO_VEC},
    {"GUI.INPUT_INT", BuiltinRet::I64, BF_NO_VEC},
    {"GUI.ITEM_DEACTIVATED_AFTER_EDIT", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.ITEM_RECT", BuiltinRet::Arr, BF_NO_VEC},
    {"GUI.LISTBOX", BuiltinRet::I64, BF_NO_VEC},
    {"GUI.MENU_ITEM", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.OPEN_POPUP", BuiltinRet::None, BF_NO_VEC},
    {"GUI.PLOT_HISTOGRAM", BuiltinRet::None, BF_NO_VEC},
    {"GUI.PLOT_LINES", BuiltinRet::None, BF_NO_VEC},
    {"GUI.POP_ID", BuiltinRet::None, BF_NO_VEC},
    {"GUI.POP_STYLE_COLOR", BuiltinRet::None, BF_NO_VEC},
    {"GUI.PROGRESS", BuiltinRet::None, BF_NO_VEC},
    {"GUI.PUSH_ID", BuiltinRet::None, BF_NO_VEC},
    {"GUI.PUSH_STYLE_COLOR", BuiltinRet::None, BF_NO_VEC},
    {"GUI.RADIO", BuiltinRet::I64, BF_NO_VEC},
    {"GUI.SAME_LINE", BuiltinRet::None, BF_NO_VEC},
    {"GUI.SELECTABLE", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.SEPARATOR", BuiltinRet::None, BF_NO_VEC},
    {"GUI.SEPARATOR_TEXT", BuiltinRet::None, BF_NO_VEC},
    {"GUI.SET_CURSOR_SCREEN_POS", BuiltinRet::None, BF_NO_VEC},
    {"GUI.SET_KEYBOARD_FOCUS", BuiltinRet::None, BF_NO_VEC},
    {"GUI.SET_NEXT_ITEM_WIDTH", BuiltinRet::None, BF_NO_VEC},
    {"GUI.SHOW_FONT_ATLAS", BuiltinRet::None, BF_NO_VEC},
    {"GUI.SLIDER", BuiltinRet::F64, BF_NO_VEC},
    {"GUI.TABLE_HEADERS_ROW", BuiltinRet::None, BF_NO_VEC},
    {"GUI.TABLE_NEXT_COLUMN", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.TABLE_NEXT_ROW", BuiltinRet::None, BF_NO_VEC},
    {"GUI.TABLE_SETUP_COLUMN", BuiltinRet::None, BF_NO_VEC},
    {"GUI.TABLE_SET_COLUMN_INDEX", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.TEXT", BuiltinRet::None, BF_NO_VEC},
    {"GUI.TEXT_WRAPPED", BuiltinRet::None, BF_NO_VEC},
    {"GUI.THEME", BuiltinRet::None, BF_NO_VEC},
    {"GUI.TOOLTIP", BuiltinRet::None, BF_NO_VEC},
    {"GUI.TREE_NODE", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.TREE_POP", BuiltinRet::None, BF_NO_VEC},
    {"GUI.WINDOW_HEIGHT", BuiltinRet::F64, BF_NO_VEC},
    {"GUI.WINDOW_WIDTH", BuiltinRet::F64, BF_NO_VEC},
    {"HELP", BuiltinRet::None, BF_NO_VEC | BF_COMPILER_HANDLES},
    {"HELP$", BuiltinRet::Unknown, BF_NO_VEC | BF_COMPILER_HANDLES},
    {"HEX$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"HISTEDGES", BuiltinRet::Arr, BF_NO_VEC},
    {"HISTOGRAM", BuiltinRet::Arr, BF_NO_VEC},
    {"HOUR", BuiltinRet::I64, BF_NONE},
    {"HTTP.CLEARCOOKIES", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.CLEARHEADERS", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.CLEARPARAMS", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.FOLLOWREDIRECTS", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.REQUEST", BuiltinRet::Handle, BF_NONE},
    {"HTTP.SERVER.LOG", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SERVER.ON_GET", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SERVER.ON_NOTFOUND", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SERVER.ON_POST", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SERVER.START", BuiltinRet::Bool, BF_NONE},
    {"HTTP.SERVER.STOP", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SERVER.WAIT", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SETCOOKIE", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SETHEADER", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SETPARAM", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.SETTIMEOUT", BuiltinRet::None, BF_NO_VEC},
    {"HTTP.STATUSCODE", BuiltinRet::I64, BF_NO_VEC},
    {"IFFT", BuiltinRet::Arr, BF_NO_VEC},
    {"IIF", BuiltinRet::Unknown, BF_NO_VEC | BF_COMPILER_HANDLES},
    {"INDEXOF", BuiltinRet::I64, BF_NO_VEC},
    {"INKEY$", BuiltinRet::Str, BF_NO_VEC},
    {"INPUTBOX$", BuiltinRet::Unknown, BF_NO_VEC},
    {"INPUT_HIDDEN$", BuiltinRet::Str, BF_NO_VEC},
    {"INSERT$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"INSTR", BuiltinRet::I64, BF_READS_ARGS},
    {"INSTR$", BuiltinRet::I64, BF_READS_ARGS},
    {"INT", BuiltinRet::I64, BF_NONE},
    {"INTEGRATE", BuiltinRet::F64, BF_NO_VEC | BF_COMPILER_HANDLES},
    {"INVERT", BuiltinRet::Arr, BF_NO_VEC},
    {"IOTA", BuiltinRet::Arr, BF_NO_VEC},
    {"ISARR", BuiltinRet::Bool, BF_NO_VEC},
    {"ISBOOL", BuiltinRet::Bool, BF_NO_VEC},
    {"ISMAP", BuiltinRet::Bool, BF_NO_VEC},
    {"ISNONE", BuiltinRet::Bool, BF_NO_VEC},
    {"ISNULL", BuiltinRet::Bool, BF_NO_VEC},
    {"ISNUM", BuiltinRet::Bool, BF_NO_VEC},
    {"ISSTR", BuiltinRet::Bool, BF_NO_VEC},
    {"JDB.CHECK$", BuiltinRet::Unknown, BF_NO_VEC},
    {"JDB.GLOBAL_GET", BuiltinRet::Unknown, BF_NO_VEC},
    {"JDB.GLOBAL_SET", BuiltinRet::None, BF_NO_VEC},
    {"JOIN", BuiltinRet::Str, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"JOY.AXIS", BuiltinRet::F64, BF_NO_VEC},
    {"JOY.BUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"JOY.COUNT", BuiltinRet::I64, BF_NO_VEC},
    {"JOY.HAT", BuiltinRet::I64, BF_NO_VEC},
    {"JOY.NAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"JSON.PARSE", BuiltinRet::Handle, BF_NO_VEC},
    {"JSON.PARSE$", BuiltinRet::Handle, BF_NO_VEC},
    {"JSON.STRINGIFY$", BuiltinRet::Unknown, BF_NO_VEC | BF_KEEPS_ARGS},
    {"KILL", BuiltinRet::None, BF_NO_VEC},
    {"LCASE", BuiltinRet::Str, BF_READS_ARGS | BF_FRESH_STR},
    {"LCASE$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LCM", BuiltinRet::I64, BF_NO_VEC},
    {"LEFT", BuiltinRet::Str, BF_FRESH_STR},
    {"LEFT$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LEN", BuiltinRet::I64, BF_NO_VEC | BF_READS_ARGS},
    {"LENV", BuiltinRet::Arr, BF_NO_VEC},
    {"LERP", BuiltinRet::F64, BF_NONE},
    {"LINE", BuiltinRet::None, BF_NO_VEC},
    {"LINSPACE", BuiltinRet::Arr, BF_NO_VEC},
    {"LIST", BuiltinRet::None, BF_NO_VEC},
    {"LIST_RECUR", BuiltinRet::None, BF_NO_VEC},
    {"LOAD", BuiltinRet::None, BF_NO_VEC},
    {"LOCATE", BuiltinRet::None, BF_NO_VEC},
    {"LOG", BuiltinRet::F64, BF_NONE},
    {"LOG10", BuiltinRet::F64, BF_NONE},
    {"LOWER$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LPAD$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LTRIM$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"MAP.CLEAR", BuiltinRet::None, BF_NO_VEC | BF_MAP_ARG1},
    {"MAP.DELETE", BuiltinRet::Unknown, BF_NO_VEC | BF_MAP_ARG1},
    {"MAP.EXISTS", BuiltinRet::Bool, BF_NO_VEC},
    {"MAP.FROM", BuiltinRet::Handle, BF_NO_VEC | BF_KEEPS_ARGS},
    {"MAP.ITEMS", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS | BF_MAP_ARG1},
    {"MAP.KEYS", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS | BF_MAP_ARG1},
    {"MAP.MERGE", BuiltinRet::None, BF_NO_VEC | BF_KEEPS_ARGS},
    {"MAP.SIZE", BuiltinRet::I64, BF_NO_VEC | BF_MAP_ARG1},
    {"MAP.VALUES", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS | BF_MAP_ARG1},
    {"MAT4.IDENTITY", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.LOOKAT", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.MUL", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.PERSPECTIVE", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.ROTATE", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.SCALE", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.TRANSLATE", BuiltinRet::Handle, BF_NO_VEC},
    {"MATH.E", BuiltinRet::F64, BF_CONST},
    {"MATH.PI", BuiltinRet::F64, BF_CONST},
    {"MATMUL", BuiltinRet::Arr, BF_NO_VEC},
    {"MAX", BuiltinRet::F64, BF_NO_VEC},
    {"MEAN", BuiltinRet::F64, BF_NO_VEC},
    {"MEDIAN", BuiltinRet::F64, BF_NO_VEC},
    {"MID", BuiltinRet::Str, BF_FRESH_STR},
    {"MID$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"MIDI.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"MIDI.OPEN_IN", BuiltinRet::I64, BF_NO_VEC},
    {"MIDI.OPEN_OUT", BuiltinRet::I64, BF_NO_VEC},
    {"MIDI.POLL", BuiltinRet::Handle, BF_NO_VEC},
    {"MIDI.PORTS", BuiltinRet::Handle, BF_NO_VEC},
    {"MIDI.SEND", BuiltinRet::Bool, BF_NONE},
    {"MIN", BuiltinRet::F64, BF_NO_VEC},
    {"MINUTE", BuiltinRet::I64, BF_NONE},
    {"MKDIR", BuiltinRet::None, BF_NO_VEC},
    {"MKTEMP$", BuiltinRet::Unknown, BF_NO_VEC},
    {"MON.DEVICES", BuiltinRet::Handle, BF_NONE},
    {"MON.FX", BuiltinRet::None, BF_NO_VEC},
    {"MON.GAIN", BuiltinRet::None, BF_NO_VEC},
    {"MON.LEVEL", BuiltinRet::Handle, BF_NO_VEC},
    {"MON.PITCH", BuiltinRet::F64, BF_NO_VEC},
    {"MON.RECLEN", BuiltinRet::F64, BF_NO_VEC},
    {"MON.RECSTART", BuiltinRet::Bool, BF_NONE},
    {"MON.RECSTOP", BuiltinRet::F64, BF_NO_VEC},
    {"MON.RUNNING", BuiltinRet::Bool, BF_NONE},
    {"MON.SCOPE", BuiltinRet::Arr, BF_NONE},
    {"MON.START", BuiltinRet::Bool, BF_NONE},
    {"MON.STOP", BuiltinRet::None, BF_NO_VEC},
    {"MONTH", BuiltinRet::I64, BF_NONE},
    {"MOUSEB", BuiltinRet::Bool, BF_NO_VEC},
    {"MOUSEX", BuiltinRet::I64, BF_NO_VEC},
    {"MOUSEY", BuiltinRet::I64, BF_NO_VEC},
    {"MSGBOX", BuiltinRet::I64, BF_NO_VEC},
    {"MUSIC.PLAY", BuiltinRet::None, BF_NO_VEC},
    {"MUSIC.STOP", BuiltinRet::None, BF_NO_VEC},
    {"MVINS", BuiltinRet::Arr, BF_NO_VEC},
    {"MVLET", BuiltinRet::Arr, BF_NO_VEC},
    {"NET.ACCEPT", BuiltinRet::I64, BF_NO_VEC},
    {"NET.ALIVE", BuiltinRet::Bool, BF_NO_VEC},
    {"NET.CLOSE", BuiltinRet::Bool, BF_NO_VEC},
    {"NET.CONNECT", BuiltinRet::I64, BF_NO_VEC},
    {"NET.ERROR$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.LISTEN", BuiltinRet::I64, BF_NO_VEC},
    {"NET.PEER$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.PORT", BuiltinRet::I64, BF_NO_VEC},
    {"NET.RECV$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.RECVFROM", BuiltinRet::Handle, BF_NO_VEC},
    {"NET.RECVLINE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.SEND", BuiltinRet::I64, BF_NO_VEC},
    {"NET.SENDTO", BuiltinRet::I64, BF_NO_VEC},
    {"NET.UDP", BuiltinRet::I64, BF_NO_VEC},
    {"NORMALIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"NOW", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"NOW_EPOCH", BuiltinRet::F64, BF_NO_VEC},
    {"OCT$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"ONES", BuiltinRet::Arr, BF_NO_VEC},
    {"OPTION", BuiltinRet::None, BF_NO_VEC},
    {"OS.ARGS", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"OS.EXEC", BuiltinRet::Handle, BF_NO_VEC},
    {"OS.FEATURE", BuiltinRet::Bool, BF_NO_VEC},
    {"OS.GETOS", BuiltinRet::Str, BF_NO_VEC},
    {"OS.GETOS$", BuiltinRet::Str, BF_NO_VEC},
    {"OS.HOSTNAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.IP$", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.LOAD", BuiltinRet::F64, BF_NO_VEC},
    {"OS.SCREENSHOT", BuiltinRet::I64, BF_NO_VEC},
    {"OUTER", BuiltinRet::Arr, BF_NO_VEC},
    {"OUTPUT.CAPTURE_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"PACK$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PACKSIZE", BuiltinRet::I64, BF_NO_VEC},
    {"PARTICLE.CLEAR", BuiltinRet::None, BF_NO_VEC},
    {"PARTICLE.COUNT", BuiltinRet::I64, BF_NO_VEC},
    {"PARTICLE.DRAW", BuiltinRet::None, BF_NO_VEC},
    {"PARTICLE.EMIT", BuiltinRet::None, BF_NO_VEC},
    {"PATH.BASENAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.DIRNAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.EXT$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.JOIN$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.NORMALIZE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PDF.TEXT$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PLACE", BuiltinRet::Arr, BF_NO_VEC},
    {"PLOTRAW", BuiltinRet::None, BF_NO_VEC},
    {"POP", BuiltinRet::Unknown, BF_NO_VEC | BF_COMPILER_HANDLES},
    {"PRINT", BuiltinRet::Unknown, BF_READS_ARGS},
    {"PRODUCT", BuiltinRet::F64, BF_NO_VEC},
    {"PSET", BuiltinRet::None, BF_NO_VEC},
    {"PUSH", BuiltinRet::I64, BF_NO_VEC | BF_KEEPS_ARGS},
    {"PWD", BuiltinRet::Str, BF_NO_VEC},
    {"PY.DIR$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PY.EVAL", BuiltinRet::Handle, BF_NO_VEC},
    {"PY.GET", BuiltinRet::Handle, BF_NO_VEC},
    {"PY.HELP$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PY.SET", BuiltinRet::Bool, BF_NO_VEC},
    {"PYTHON$", BuiltinRet::Unknown, BF_NO_VEC},
    {"QR", BuiltinRet::Handle, BF_NO_VEC},
    {"RANDOM", BuiltinRet::F64, BF_NONE},
    {"RANDOMSEED", BuiltinRet::None, BF_NO_VEC},
    {"RANGE", BuiltinRet::Arr, BF_NO_VEC},
    {"REACT_BIND", BuiltinRet::None, BF_NO_VEC},
    {"RECT", BuiltinRet::None, BF_NO_VEC},
    {"RECUR", BuiltinRet::I64, BF_NO_VEC},
    {"REDUCE", BuiltinRet::F64, BF_NO_VEC},
    {"REGEX.FINDALL", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REGEX.MATCH", BuiltinRet::Handle, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REGEX.REPLACE", BuiltinRet::Str, BF_NO_VEC},
    {"REGEX_MATCH", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REGEX_REPLACE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"RELEASEALL", BuiltinRet::None, BF_NO_VEC},
    {"RELEASEOBJECT", BuiltinRet::None, BF_NO_VEC},
    {"REPEAT$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"REPLACE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"RESHAPE", BuiltinRet::Arr, BF_NO_VEC},
    {"REVERSE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REVERSE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"RIGHT", BuiltinRet::Str, BF_FRESH_STR},
    {"RIGHT$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"RMDIR", BuiltinRet::None, BF_NO_VEC},
    {"RND", BuiltinRet::F64, BF_NONE},
    {"RNG.FILL", BuiltinRet::Arr, BF_NO_VEC},
    {"RNG.FREE", BuiltinRet::None, BF_NO_VEC},
    {"RNG.INT", BuiltinRet::I64, BF_NO_VEC},
    {"RNG.NEW", BuiltinRet::I64, BF_NO_VEC},
    {"RNG.NEXT", BuiltinRet::F64, BF_NO_VEC},
    {"ROTATE", BuiltinRet::Arr, BF_NO_VEC},
    {"ROTL", BuiltinRet::I64, BF_NO_VEC},
    {"ROTR", BuiltinRet::I64, BF_NO_VEC},
    {"ROUND", BuiltinRet::F64, BF_NONE},
    {"ROUNDED_RECT", BuiltinRet::None, BF_NO_VEC},
    {"RPAD$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"RTRIM$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"SAVE", BuiltinRet::None, BF_NO_VEC},
    {"SCAN", BuiltinRet::Arr, BF_NO_VEC},
    {"SCREEN", BuiltinRet::None, BF_NO_VEC},
    {"SCREENFLIP", BuiltinRet::None, BF_NO_VEC},
    {"SCREENHEIGHT", BuiltinRet::I64, BF_NO_VEC},
    {"SCREENWIDTH", BuiltinRet::I64, BF_NO_VEC},
    {"SECOND", BuiltinRet::I64, BF_NONE},
    {"SELECT", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"SERIAL.AVAILABLE", BuiltinRet::I64, BF_NO_VEC},
    {"SERIAL.CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"SERIAL.FLUSH", BuiltinRet::None, BF_NO_VEC},
    {"SERIAL.OPEN", BuiltinRet::Handle, BF_NO_VEC | BF_READS_ARGS},
    {"SERIAL.WRITE", BuiltinRet::I64, BF_NO_VEC},
    {"SETENV", BuiltinRet::None, BF_NO_VEC},
    {"SETFONT", BuiltinRet::None, BF_NO_VEC},
    {"SETLOCALE", BuiltinRet::None, BF_NO_VEC},
    {"SFX.LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"SFX.PLAY", BuiltinRet::None, BF_NO_VEC},
    {"SGN", BuiltinRet::I64, BF_NONE},
    {"SHIFT", BuiltinRet::Arr, BF_NO_VEC},
    {"SHL", BuiltinRet::I64, BF_NONE},
    {"SHR", BuiltinRet::I64, BF_NONE},
    {"SHUFFLE", BuiltinRet::Arr, BF_NO_VEC},
    {"SIGN", BuiltinRet::I64, BF_NONE},
    {"SIN", BuiltinRet::F64, BF_NONE},
    {"SINH", BuiltinRet::F64, BF_NONE},
    {"SLEEP", BuiltinRet::None, BF_NO_VEC},
    {"SLICE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"SOLVE", BuiltinRet::Arr, BF_NO_VEC},
    {"SORT", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"SOUND.BITCRUSH", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.BPM", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.COMPRESSOR", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.DEBUG", BuiltinRet::Handle, BF_NO_VEC},
    {"SOUND.DELAY", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.DELAYSEND", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.DISTORTION", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.EQ", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.FILTER", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.FM", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.GAIN", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.GET_BUS_WAVE", BuiltinRet::Arr, BF_NO_VEC},
    {"SOUND.GET_WAVE", BuiltinRet::Arr, BF_NO_VEC},
    {"SOUND.INIT", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.LFO", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.NOTE", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.PAN", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.PLAY", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.PLAYBUFFER", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.QUEUED", BuiltinRet::I64, BF_NO_VEC},
    {"SOUND.RELEASE", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.RENDER", BuiltinRet::Arr, BF_NONE},
    {"SOUND.RESET", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.REVERB", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.REVERBSEND", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.RINGMOD", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.SAMPLE", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.SCALE", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.SEQ", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.SHUTDOWN", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.SIDECHAIN", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.STATS", BuiltinRet::Str, BF_NONE},
    {"SOUND.STOP", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.UNISON", BuiltinRet::None, BF_NO_VEC},
    {"SOUND.VOICE", BuiltinRet::None, BF_NO_VEC},
    {"SPACE$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"SPLIT", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"SPRITE.ALPHA", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.ANIM", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.COLLISION", BuiltinRet::Bool, BF_NO_VEC},
    {"SPRITE.COLLISIONS", BuiltinRet::Arr, BF_NO_VEC},
    {"SPRITE.COLLISION_FIRST", BuiltinRet::I64, BF_NO_VEC},
    {"SPRITE.CREATE", BuiltinRet::I64, BF_NO_VEC},
    {"SPRITE.DELETE", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.DRAW", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.DRAW_ALL", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.FLIP", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.FRAME", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.GET_VX", BuiltinRet::F64, BF_NO_VEC},
    {"SPRITE.GET_VY", BuiltinRet::F64, BF_NO_VEC},
    {"SPRITE.GET_X", BuiltinRet::F64, BF_NO_VEC},
    {"SPRITE.GET_Y", BuiltinRet::F64, BF_NO_VEC},
    {"SPRITE.GRAVITY", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.GROUP", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.HEIGHT", BuiltinRet::F64, BF_NO_VEC},
    {"SPRITE.LAND", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.LOAD", BuiltinRet::I64, BF_NO_VEC},
    {"SPRITE.MOVE", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.ON_GROUND", BuiltinRet::Bool, BF_NO_VEC},
    {"SPRITE.PLAY", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.PLAYING", BuiltinRet::Bool, BF_NO_VEC},
    {"SPRITE.POS", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.ROTATE", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.SAVE", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.SCALE", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.SETBUFFER", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.SETPIXEL", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.SET_ORIGIN", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.STOP", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.UPDATE", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.VELOCITY", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.VISIBLE", BuiltinRet::None, BF_NO_VEC},
    {"SPRITE.WIDTH", BuiltinRet::F64, BF_NO_VEC},
    {"SPRITE.ZORDER", BuiltinRet::None, BF_NO_VEC},
    {"SQL.CLOSE", BuiltinRet::Bool, BF_NO_VEC},
    {"SQL.COLUMNS", BuiltinRet::Arr, BF_NO_VEC},
    {"SQL.ERRMSG$", BuiltinRet::Unknown, BF_NO_VEC},
    {"SQL.EXEC", BuiltinRet::I64, BF_NO_VEC},
    {"SQL.OPEN", BuiltinRet::I64, BF_NO_VEC},
    {"SQL.QUERY", BuiltinRet::Unknown, BF_NO_VEC | BF_COMPILER_HANDLES},
    {"SQL.TABLE", BuiltinRet::Arr, BF_NO_VEC},
    {"SQR", BuiltinRet::F64, BF_NONE},
    {"STACK", BuiltinRet::Arr, BF_NO_VEC},
    {"STARTSWITH", BuiltinRet::Bool, BF_READS_ARGS},
    {"STDEV", BuiltinRet::F64, BF_NO_VEC},
    {"STR", BuiltinRet::Str, BF_FRESH_STR},
    {"STR$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"SUM", BuiltinRet::F64, BF_NO_VEC},
    {"SVD", BuiltinRet::Handle, BF_NO_VEC},
    {"SYS.CALL", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.INB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.OUTB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.PEEK", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.PEEKB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.PEEKW", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.POKE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.POKEB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.POKEW", BuiltinRet::Unknown, BF_NO_VEC},
    {"TAKE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"TAKE_WHILE", BuiltinRet::Arr, BF_NO_VEC},
    {"TALLY", BuiltinRet::Arr, BF_NO_VEC},
    {"TAN", BuiltinRet::F64, BF_NONE},
    {"TANH", BuiltinRet::F64, BF_NONE},
    {"TEXT", BuiltinRet::None, BF_NO_VEC},
    {"THREAD.GETRESULT", BuiltinRet::Handle, BF_NO_VEC},
    {"THREAD.ISDONE", BuiltinRet::Bool, BF_NO_VEC},
    {"TICK", BuiltinRet::F64, BF_NO_VEC},
    {"TILED.COLLIDES", BuiltinRet::Bool, BF_NONE},
    {"TILED.DRAW", BuiltinRet::None, BF_NO_VEC},
    {"TILED.DRAW_LAYER", BuiltinRet::None, BF_NO_VEC},
    {"TILED.FREE", BuiltinRet::None, BF_NO_VEC},
    {"TILED.LAYERS$", BuiltinRet::Arr, BF_NONE},
    {"TILED.LOAD", BuiltinRet::Bool, BF_NONE},
    {"TILED.OBJECTS", BuiltinRet::Handle, BF_NONE},
    {"TILED.PROPERTIES", BuiltinRet::Handle, BF_NONE},
    {"TILED.SIZE", BuiltinRet::Arr, BF_NONE},
    {"TILED.TILE_AT", BuiltinRet::I64, BF_NO_VEC},
    {"TILED.TILE_SIZE", BuiltinRet::Arr, BF_NONE},
    {"TILED.UPDATE", BuiltinRet::None, BF_NO_VEC},
    {"TILEMAP.COLLIDES", BuiltinRet::Bool, BF_NO_VEC},
    {"TILEMAP.CREATE", BuiltinRet::None, BF_NO_VEC},
    {"TILEMAP.DRAW", BuiltinRet::None, BF_NO_VEC},
    {"TILEMAP.GET", BuiltinRet::I64, BF_NO_VEC},
    {"TILEMAP.SET", BuiltinRet::None, BF_NO_VEC},
    {"TILEMAP.SIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"TILEMAP.TILE_AT", BuiltinRet::I64, BF_NO_VEC},
    {"TIME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TOGGLE_FULLSCREEN", BuiltinRet::None, BF_NO_VEC},
    {"TONUM", BuiltinRet::F64, BF_READS_ARGS},
    {"TOSTR", BuiltinRet::Str, BF_READS_ARGS | BF_FRESH_STR},
    {"TRANSPOSE", BuiltinRet::Arr, BF_NO_VEC},
    {"TRIM", BuiltinRet::Str, BF_READS_ARGS | BF_FRESH_STR},
    {"TRIM$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"TROFF", BuiltinRet::None, BF_NO_VEC},
    {"TRON", BuiltinRet::None, BF_NO_VEC},
    {"TRUNC", BuiltinRet::F64, BF_NONE},
    {"TUI.BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.BG_COLOR", BuiltinRet::None, BF_NO_VEC},
    {"TUI.BORDER_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.BORDER_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.BUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.CANVAS_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.CANVAS_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.CHECKBOX", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.COLOR", BuiltinRet::None, BF_NO_VEC},
    {"TUI.DROPDOWN", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.EXIT", BuiltinRet::None, BF_NO_VEC},
    {"TUI.GAUGE", BuiltinRet::None, BF_NO_VEC},
    {"TUI.GRID_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.GRID_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.HBOX_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.HBOX_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.HEADING", BuiltinRet::None, BF_NO_VEC},
    {"TUI.HEIGHT", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.INPUT", BuiltinRet::Str, BF_NO_VEC},
    {"TUI.INPUT_DOUBLE", BuiltinRet::F64, BF_NO_VEC},
    {"TUI.INPUT_INT", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.KEY$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.LAST_RENDER_MS", BuiltinRet::F64, BF_NO_VEC},
    {"TUI.LINE", BuiltinRet::None, BF_NO_VEC},
    {"TUI.LINK", BuiltinRet::None, BF_NO_VEC},
    {"TUI.MENU", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.MENUBAR_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.MENUBAR_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.MENUITEM", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.MODAL_BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.MODAL_CLOSE", BuiltinRet::None, BF_NO_VEC},
    {"TUI.MODAL_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.MODAL_OPEN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.MOUSE_BTN", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.MOUSE_WHEEL", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.MOUSE_X", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.MOUSE_Y", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.ON", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.PARAGRAPH", BuiltinRet::None, BF_NO_VEC},
    {"TUI.PIXEL", BuiltinRet::None, BF_NO_VEC},
    {"TUI.POP_COLOR", BuiltinRet::None, BF_NO_VEC},
    {"TUI.PROGRESS", BuiltinRet::None, BF_NO_VEC},
    {"TUI.QUIT", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.RADIO", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.RENDER", BuiltinRet::None, BF_NO_VEC},
    {"TUI.RENDER_HEADLESS$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SAME_LINE", BuiltinRet::None, BF_NO_VEC},
    {"TUI.SELECTABLE", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.SEPARATOR", BuiltinRet::None, BF_NO_VEC},
    {"TUI.SEPARATOR_TEXT", BuiltinRet::None, BF_NO_VEC},
    {"TUI.SIZE", BuiltinRet::None, BF_NO_VEC},
    {"TUI.SLIDER", BuiltinRet::F64, BF_NO_VEC},
    {"TUI.SPACER", BuiltinRet::None, BF_NO_VEC},
    {"TUI.SPINNER", BuiltinRet::None, BF_NO_VEC},
    {"TUI.STYLE_POP", BuiltinRet::None, BF_NO_VEC},
    {"TUI.STYLE_PUSH", BuiltinRet::None, BF_NO_VEC},
    {"TUI.SUBMENU_BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.SUBMENU_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.TABLE_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.TABLE_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.TABLE_ROW", BuiltinRet::None, BF_NO_VEC},
    {"TUI.TAB_BAR_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.TAB_BAR_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.TAB_BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.TAB_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.TEXT", BuiltinRet::None, BF_NO_VEC},
    {"TUI.THEME", BuiltinRet::None, BF_NO_VEC},
    {"TUI.VBOX_BEGIN", BuiltinRet::None, BF_NO_VEC},
    {"TUI.VBOX_END", BuiltinRet::None, BF_NO_VEC},
    {"TUI.VERSION$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.WAIT_EVENT", BuiltinRet::Str, BF_NO_VEC},
    {"TUI.WIDTH", BuiltinRet::I64, BF_NO_VEC},
    {"TURTLE.BACKWARD", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.CLEAR", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.DRAW", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.FORWARD", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.HOME", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.LEFT", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.PENDOWN", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.PENUP", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.RIGHT", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.SETHEADING", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.SETPOS", BuiltinRet::None, BF_NO_VEC},
    {"TURTLE.SET_COLOR", BuiltinRet::None, BF_NO_VEC},
    {"TXTREADER$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TXTWRITER", BuiltinRet::None, BF_NO_VEC},
    {"TYPEOF", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_COMPILER_HANDLES},
    {"UCASE", BuiltinRet::Str, BF_READS_ARGS | BF_FRESH_STR},
    {"UCASE$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"UNIQUE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"UNPACK", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"UNREACT", BuiltinRet::None, BF_NO_VEC},
    {"UPPER$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"VAL", BuiltinRet::F64, BF_READS_ARGS},
    {"VARIANCE", BuiltinRet::F64, BF_NO_VEC},
    {"VARS", BuiltinRet::None, BF_NO_VEC},
    {"VBCRLF", BuiltinRet::Str, BF_CONST},
    {"VBNEWLINE", BuiltinRet::Str, BF_CONST},
    {"VBTAB", BuiltinRet::Str, BF_CONST},
    {"WAITKEY$", BuiltinRet::Unknown, BF_NO_VEC},
    {"WAV.INFO", BuiltinRet::Handle, BF_NONE},
    {"WAV.READ", BuiltinRet::Handle, BF_NONE},
    {"WAV.RECLEN", BuiltinRet::F64, BF_NO_VEC},
    {"WAV.RECORD", BuiltinRet::Handle, BF_NONE},
    {"WAV.RECSTART", BuiltinRet::Bool, BF_NONE},
    {"WAV.RECSTOP", BuiltinRet::Handle, BF_NONE},
    {"WAV.WRITE", BuiltinRet::Bool, BF_NO_VEC},
    {"WEEKDAY", BuiltinRet::I64, BF_NONE},
    {"XSORT", BuiltinRet::Arr, BF_NO_VEC},
    {"YEAR", BuiltinRet::I64, BF_NONE},
    {"YIELD", BuiltinRet::None, BF_NO_VEC},
    {"ZEROS", BuiltinRet::Arr, BF_NO_VEC},
    {"ZIP", BuiltinRet::Arr, BF_NO_VEC},
    {"ZIP.LIST", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"ZIP.READ", BuiltinRet::Handle, BF_NO_VEC},
    {"ZIP.WRITE", BuiltinRet::I64, BF_NO_VEC},
    {"__EVENT_ON", BuiltinRet::None, BF_NO_VEC},
    {"__EVENT_RAISE", BuiltinRet::None, BF_NO_VEC},
    {"__FFI_DECLARE", BuiltinRet::None, BF_NO_VEC},
    {"__MAKE_UDT_ARRAY__", BuiltinRet::Unknown, BF_NO_VEC},
};

// Compares a name case-insensitively with an upper-case table name:
// negative, zero or positive like strcmp.
inline int builtin_name_cmp(std::string_view name, const char* table_name) {
    size_t i = 0;
    for (; i < name.size() && table_name[i]; i++) {
        unsigned char a = (unsigned char)name[i];
        if (a >= 'a' && a <= 'z') a = (unsigned char)(a - 'a' + 'A');
        unsigned char b = (unsigned char)table_name[i];
        if (a != b) return a < b ? -1 : 1;
    }
    if (i < name.size()) return 1;
    return table_name[i] ? -1 : 0;
}

constexpr bool builtin_sigs_sorted() {
    for (size_t i = 1; i < sizeof(kBuiltinSigs) / sizeof(kBuiltinSigs[0]); i++) {
        const char* a = kBuiltinSigs[i - 1].name;
        const char* b = kBuiltinSigs[i].name;
        size_t k = 0;
        while (a[k] && a[k] == b[k]) k++;
        if ((unsigned char)a[k] >= (unsigned char)b[k]) return false;
    }
    return true;
}
static_assert(builtin_sigs_sorted(), "kBuiltinSigs must be sorted by name, without duplicates");

// Case-insensitive; nullptr for a name the table does not list.
inline const BuiltinSig* builtin_sig(std::string_view name) {
    size_t lo = 0, hi = sizeof(kBuiltinSigs) / sizeof(kBuiltinSigs[0]);
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int c = builtin_name_cmp(name, kBuiltinSigs[mid].name);
        if (c == 0) return &kBuiltinSigs[mid];
        if (c < 0) hi = mid; else lo = mid + 1;
    }
    return nullptr;
}

inline BuiltinRet builtin_ret(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s ? s->ret : BuiltinRet::Unknown;
}

inline bool builtin_is(std::string_view name, BuiltinRet ret) {
    return builtin_ret(name) == ret;
}

inline bool builtin_has(std::string_view name, BuiltinFlags flag) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & flag);
}

inline bool builtin_returns_date(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_DATE);
}

inline bool builtin_no_vectorize(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_NO_VEC);
}

inline bool builtin_reads_args(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_READS_ARGS);
}

inline bool builtin_fresh_string(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_FRESH_STR);
}
