#pragma once
// Return kind and call behaviour of each builtin, shared by the VM and the
// native compiler. Sorted by name; lookup is a binary search over the table.
// tools/check_builtin_sigs.jdb checks the names against help.txt.

#include <cstddef>
#include <cstdint>
#include <string_view>

enum class BuiltinRet : uint8_t {
    Unknown,  // not listed
    F64,
    I64,
    Bool,
    Str,      // listed only for names without a trailing $
    Arr,      // flat JdbArray
    Handle,   // VM Value in the value store: maps, tensors, mixed kinds
};

enum BuiltinFlags : uint8_t {
    BF_NONE = 0,
    BF_DATE = 1,    // answers a date
    BF_NO_VEC = 2,      // takes an array argument whole instead of per element
    BF_READS_ARGS = 4,     // reads its string arguments without keeping them
    BF_FRESH_STR = 8,      // answers a newly allocated string the caller owns
    BF_KEEPS_ARGS = 16,    // stores its arguments in a container or channel
    BF_TAGGED_CELLS = 32,  // answers an array whose cells differ in kind
    BF_MAP_ARG1 = 64,      // takes a map as its first argument
    BF_CONST = 128,        // a built-in constant, not assignable
};

struct BuiltinSig {
    const char* name;
    BuiltinRet ret;
    uint8_t flags;
};

inline constexpr BuiltinSig kBuiltinSigs[] = {
    {"AGG", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.ARGMAX", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CHAT", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CHAT_JSON", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CHAT_RAW", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CHAT_STREAM", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CHAT_TOKENS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_ADD", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_ADD_BATCH", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_BUILD_INDEX", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_CREATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_FREE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_INFO", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_PREDICT", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLASSIFIER_SAVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLEAR_GRAMMAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.CLEAR_HISTORY", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.COSINE_SIM", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.DETOKENIZE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.EMBED", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.EMBED_LLM", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.FREE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.FREE_LLM", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.GET_HISTORY", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.INFO", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.LIST", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.LLM_INFO", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.LOAD_EMBEDDINGS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.LOAD_LLM", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.NORMALIZE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_ADD", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_ADD_DIR", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_ADD_FILE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_BUILD_INDEX", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_CLEAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_CREATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_FREE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_INFO", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_QUERY", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_QUERY_FULL", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.RAG_QUERY_STREAM", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_SAVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.RAG_SEARCH", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.RUN", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.SET", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.SET_GRAMMAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.SET_JSON_MODE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.SIMILARITY", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.SOFTMAX", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TENSOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOKENIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"AI.TOKEN_COUNT", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOOL_ADD", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOOL_CHAT", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOOL_LIST", BuiltinRet::Handle, BF_NO_VEC},
    {"AI.TOOL_REMOVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AI.TOPK", BuiltinRet::Arr, BF_NO_VEC},
    {"ALL", BuiltinRet::I64, BF_NO_VEC},
    {"ANY", BuiltinRet::I64, BF_NO_VEC},
    {"APPEND", BuiltinRet::Arr, BF_NO_VEC | BF_KEEPS_ARGS | BF_TAGGED_CELLS},
    {"ASC", BuiltinRet::Unknown, BF_READS_ARGS},
    {"AUDIO.CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.FREE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.FREEMUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.INIT", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.LOADMUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.LOADWAV", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.PAUSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.PAUSEMUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.PLAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.PLAYMUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.RESUME", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.RESUMEMUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.STOP", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.STOPMUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.VOLUME", BuiltinRet::Unknown, BF_NO_VEC},
    {"AUDIO.VOLUMEMUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"AWAIT", BuiltinRet::Handle, BF_NO_VEC},
    {"BIN$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"BINREADER$", BuiltinRet::Unknown, BF_NO_VEC},
    {"BINWRITER", BuiltinRet::Unknown, BF_NO_VEC},
    {"CAM.BOUNDS", BuiltinRet::Unknown, BF_NO_VEC},
    {"CAM.FOLLOW", BuiltinRet::Unknown, BF_NO_VEC},
    {"CAM.SET", BuiltinRet::Unknown, BF_NO_VEC},
    {"CAM.SHAKE", BuiltinRet::Unknown, BF_NO_VEC},
    {"CAM.X", BuiltinRet::Unknown, BF_NO_VEC},
    {"CAM.Y", BuiltinRet::Unknown, BF_NO_VEC},
    {"CD", BuiltinRet::Unknown, BF_NO_VEC},
    {"CDATE", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"CDBL", BuiltinRet::Unknown, BF_READS_ARGS},
    {"CHAN.CAP", BuiltinRet::Unknown, BF_NO_VEC},
    {"CHAN.CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"CHAN.IS_CLOSED", BuiltinRet::Bool, BF_NO_VEC},
    {"CHAN.IS_EOF", BuiltinRet::Bool, BF_NO_VEC},
    {"CHAN.IS_TIMEOUT", BuiltinRet::Bool, BF_NO_VEC},
    {"CHAN.LEN", BuiltinRet::Unknown, BF_NO_VEC},
    {"CHAN.OPEN", BuiltinRet::Unknown, BF_NO_VEC},
    {"CHAN.RECV", BuiltinRet::Handle, BF_NO_VEC},
    {"CHAN.SELECT", BuiltinRet::Unknown, BF_NO_VEC},
    {"CHAN.SEND", BuiltinRet::Unknown, BF_NO_VEC | BF_KEEPS_ARGS},
    {"CHAN.TRY_RECV", BuiltinRet::Handle, BF_NO_VEC},
    {"CHR", BuiltinRet::Unknown, BF_FRESH_STR},
    {"CHR$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"CHUNK", BuiltinRet::Arr, BF_NO_VEC},
    {"CINT", BuiltinRet::Unknown, BF_READS_ARGS},
    {"CIRCLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"CIRCLE_SECTOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"CLEAR_RECUR", BuiltinRet::Unknown, BF_NO_VEC},
    {"CLIPBOARD.GET$", BuiltinRet::Str, BF_NO_VEC},
    {"CLIPBOARD.SET", BuiltinRet::Unknown, BF_NO_VEC},
    {"CLNG", BuiltinRet::Unknown, BF_READS_ARGS},
    {"CLS", BuiltinRet::Unknown, BF_NO_VEC},
    {"CODEC.BASE64_DECODE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.BASE64_ENCODE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.CRC32", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.CRC32$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.DEFLATE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.HMAC$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.INFLATE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.PBKDF2$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.RANDOMBYTES$", BuiltinRet::Unknown, BF_NO_VEC},
    {"CODEC.SHA256$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"CODEC.UUID$", BuiltinRet::Unknown, BF_NO_VEC},
    {"COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"COLORDIALOG", BuiltinRet::Unknown, BF_NO_VEC},
    {"CONVOLVE", BuiltinRet::Arr, BF_NO_VEC},
    {"COPYV", BuiltinRet::Unknown, BF_NO_VEC},
    {"COUNT", BuiltinRet::I64, BF_NO_VEC},
    {"CROSS", BuiltinRet::F64, BF_NO_VEC},
    {"CSVHEADER", BuiltinRet::Arr, BF_NO_VEC},
    {"CSVREADER", BuiltinRet::Arr, BF_NO_VEC},
    {"CSVWRITER", BuiltinRet::Unknown, BF_NO_VEC},
    {"CUMPROD", BuiltinRet::Arr, BF_NO_VEC},
    {"CUMSUM", BuiltinRet::Arr, BF_NO_VEC},
    {"CURSOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"CVDATE", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"DATE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"DATE.PARTS", BuiltinRet::Handle, BF_NO_VEC},
    {"DATE.UTC", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"DATEADD", BuiltinRet::Str, BF_DATE},
    {"DATERANGE", BuiltinRet::Arr, BF_NO_VEC},
    {"DEBUG.ASSERT", BuiltinRet::Unknown, BF_NO_VEC},
    {"DEBUG.PRINT", BuiltinRet::Unknown, BF_NO_VEC},
    {"DET", BuiltinRet::Unknown, BF_NO_VEC},
    {"DIFF", BuiltinRet::Arr, BF_NO_VEC},
    {"DIR", BuiltinRet::Unknown, BF_NO_VEC},
    {"DIR$", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"DISTANCE", BuiltinRet::Unknown, BF_NO_VEC},
    {"DOT", BuiltinRet::F64, BF_NO_VEC},
    {"DRAWCOLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"DROP", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"DROP_WHILE", BuiltinRet::Arr, BF_NO_VEC},
    {"E", BuiltinRet::Unknown, BF_CONST},
    {"EIG", BuiltinRet::Handle, BF_NO_VEC},
    {"ELLIPSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"ENDSWITH", BuiltinRet::Bool, BF_READS_ARGS},
    {"ENUMERATE", BuiltinRet::Arr, BF_NO_VEC},
    {"EOMONTH", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"EVAL", BuiltinRet::Unknown, BF_NO_VEC},
    {"EXECUTE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FFT", BuiltinRet::Arr, BF_NO_VEC},
    {"FILE.AT_EOF", BuiltinRet::Bool, BF_NO_VEC},
    {"FILE.CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.EXISTS", BuiltinRet::Bool, BF_NO_VEC},
    {"FILE.ISDIR", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.OPEN_LINES", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.OPEN_TAIL", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.READLINE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.SIZE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.STAT", BuiltinRet::Handle, BF_NO_VEC},
    {"FILE.STREAM_LINES", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILE.STREAM_TAIL", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILEOPEN$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILESAVE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILLV", BuiltinRet::Unknown, BF_NO_VEC},
    {"FILTER", BuiltinRet::Unknown, BF_NO_VEC},
    {"FIND_IN_ARRAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"FLATTEN", BuiltinRet::Arr, BF_NO_VEC},
    {"FONTDIALOG$", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.BUTTON", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.CHECKBOX", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.CHILD", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.COMBO", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.CREATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.DATETIME", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.DOEVENTS", BuiltinRet::Bool, BF_NO_VEC},
    {"FORM.FIND", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.FRAME", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.GET", BuiltinRet::Handle, BF_NO_VEC},
    {"FORM.LABEL", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.LINE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.LISTBOX", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.LISTVIEW", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.MDI", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.MENU", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.NODE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.PICTURE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.POPUP", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.PROGRESS", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.RADIO", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.RICHTEXT", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.RUN", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.SET", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.SHAPE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.SHOW", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.SLIDER", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.STATUSBAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.TABPAGE", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.TABS", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.TEXTBOX", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.TIMER", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.TOOLBAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.TREEVIEW", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORM.UPDOWN", BuiltinRet::Unknown, BF_NO_VEC},
    {"FORMAT$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"FORMAT_DATE", BuiltinRet::Str, BF_NONE},
    {"FRMV$", BuiltinRet::Unknown, BF_NO_VEC | BF_FRESH_STR},
    {"FUNCS", BuiltinRet::Unknown, BF_NO_VEC},
    {"FX.ADD", BuiltinRet::Bool, BF_NONE},
    {"FX.MIX", BuiltinRet::Bool, BF_NONE},
    {"FX.PROCESS", BuiltinRet::Unknown, BF_NO_VEC},
    {"FX.SET", BuiltinRet::Bool, BF_NONE},
    {"FX.SPLIT", BuiltinRet::Bool, BF_NONE},
    {"GCD", BuiltinRet::Unknown, BF_NO_VEC},
    {"GETENV$", BuiltinRet::Unknown, BF_NO_VEC},
    {"GETX", BuiltinRet::Unknown, BF_NO_VEC},
    {"GETY", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.CAPTURE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.COLOR_TO_ALPHA", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.DELAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.DRAWIMAGE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.DRAWIMAGE_EX", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.DRAWIMAGE_REGION", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.DRAW_CAPTURE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.FADE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.FREEIMAGE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.HSV_RGB", BuiltinRet::Arr, BF_NO_VEC},
    {"GFX.KEYSTATE", BuiltinRet::Bool, BF_NO_VEC},
    {"GFX.LOADIMAGE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.MOUSEBUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"GFX.MOUSEX", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.MOUSEY", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.PLOT_POINTS", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.PLOT_POINTS_TEX", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.POLLEVENT", BuiltinRet::Str, BF_NO_VEC},
    {"GFX.SAVE_IMAGE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.SAVE_SCREENSHOT", BuiltinRet::Unknown, BF_NO_VEC},
    {"GFX.TEXTSIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"GFX.TICKS", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.ATTRIB", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.BUFFER.DELETE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.CLEAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.DISABLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.DRAW.LINES", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.DRAW.TRIS", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.DRAW.TRIS.IDX", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.EBO", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.ENABLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.FLIP", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.SHADER", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.SHADER.DELETE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.TEX.BIND", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.TEX.DELETE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.TEX.LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.UNIFORM.F1", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.UNIFORM.F3", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.UNIFORM.F4", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.UNIFORM.I1", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.UNIFORM.MAT4", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.USE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.VAO", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.VAO.BIND", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.VAO.DELETE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.VBO", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.VBO.BIND", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.VIEWPORT", BuiltinRet::Unknown, BF_NO_VEC},
    {"GL.WINDOW", BuiltinRet::Unknown, BF_NO_VEC},
    {"GRADE", BuiltinRet::Arr, BF_NO_VEC},
    {"GROUPBY", BuiltinRet::Handle, BF_NO_VEC},
    {"GUI.BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_CHILD", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.BEGIN_MAIN_MENU_BAR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_MENU", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_MENU_BAR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_POPUP", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_POPUP_MODAL", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_TABLE", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_TAB_BAR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BEGIN_TAB_ITEM", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.BUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.CHECKBOX", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.CLOSE_CURRENT_POPUP", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.COL", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.COLLAPSING_HEADER", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.COLOR", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.COMBO", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.DUMMY", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_CHILD", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_MAIN_MENU_BAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_MENU", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_MENU_BAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_POPUP", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_TABLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_TAB_BAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.END_TAB_ITEM", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.FLAG", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.HELPMARKER", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.IMAGE", BuiltinRet::Bool, BF_NONE},
    {"GUI.INPUT", BuiltinRet::Str, BF_NO_VEC},
    {"GUI.INPUT_DOUBLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.INPUT_INT", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.ITEM_DEACTIVATED_AFTER_EDIT", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.ITEM_RECT", BuiltinRet::Arr, BF_NO_VEC},
    {"GUI.LISTBOX", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.MENU_ITEM", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.OPEN_POPUP", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.PLOT_HISTOGRAM", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.PLOT_LINES", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.POP_ID", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.POP_STYLE_COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.PROGRESS", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.PUSH_ID", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.PUSH_STYLE_COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.RADIO", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SAME_LINE", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SELECTABLE", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.SEPARATOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SEPARATOR_TEXT", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SET_CURSOR_SCREEN_POS", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SET_KEYBOARD_FOCUS", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SET_NEXT_ITEM_WIDTH", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SHOW_FONT_ATLAS", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.SLIDER", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.TABLE_HEADERS_ROW", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.TABLE_NEXT_COLUMN", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.TABLE_NEXT_ROW", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.TABLE_SETUP_COLUMN", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.TABLE_SET_COLUMN_INDEX", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.TEXT", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.THEME", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.TOOLTIP", BuiltinRet::Unknown, BF_NO_VEC},
    {"GUI.TREE_NODE", BuiltinRet::Bool, BF_NO_VEC},
    {"GUI.TREE_POP", BuiltinRet::Unknown, BF_NO_VEC},
    {"HELP", BuiltinRet::Unknown, BF_NO_VEC},
    {"HELP$", BuiltinRet::Unknown, BF_NO_VEC},
    {"HEX$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"HISTEDGES", BuiltinRet::Arr, BF_NO_VEC},
    {"HISTOGRAM", BuiltinRet::Arr, BF_NO_VEC},
    {"HTTP.REQUEST", BuiltinRet::Handle, BF_NONE},
    {"IFFT", BuiltinRet::Arr, BF_NO_VEC},
    {"IIF", BuiltinRet::Unknown, BF_NO_VEC},
    {"INDEXOF", BuiltinRet::I64, BF_NO_VEC},
    {"INKEY$", BuiltinRet::Str, BF_NO_VEC},
    {"INPUTBOX$", BuiltinRet::Unknown, BF_NO_VEC},
    {"INSERT$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"INSTR", BuiltinRet::Unknown, BF_READS_ARGS},
    {"INTEGRATE", BuiltinRet::Arr, BF_NO_VEC},
    {"INVERT", BuiltinRet::Arr, BF_NO_VEC},
    {"IOTA", BuiltinRet::Arr, BF_NO_VEC},
    {"ISARR", BuiltinRet::Unknown, BF_NO_VEC},
    {"ISBOOL", BuiltinRet::Unknown, BF_NO_VEC},
    {"ISMAP", BuiltinRet::Unknown, BF_NO_VEC},
    {"ISNONE", BuiltinRet::Unknown, BF_NO_VEC},
    {"ISNULL", BuiltinRet::Unknown, BF_NO_VEC},
    {"ISNUM", BuiltinRet::Unknown, BF_NO_VEC},
    {"ISSTR", BuiltinRet::Unknown, BF_NO_VEC},
    {"JDB.CHECK$", BuiltinRet::Unknown, BF_NO_VEC},
    {"JDB.GLOBAL_GET", BuiltinRet::Unknown, BF_NO_VEC},
    {"JDB.GLOBAL_SET", BuiltinRet::Unknown, BF_NO_VEC},
    {"JOIN", BuiltinRet::Str, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"JOY.AXIS", BuiltinRet::Unknown, BF_NO_VEC},
    {"JOY.BUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"JOY.COUNT", BuiltinRet::Unknown, BF_NO_VEC},
    {"JOY.HAT", BuiltinRet::Unknown, BF_NO_VEC},
    {"JOY.NAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"JSON.PARSE$", BuiltinRet::Handle, BF_NO_VEC},
    {"JSON.STRINGIFY$", BuiltinRet::Unknown, BF_NO_VEC | BF_KEEPS_ARGS},
    {"KILL", BuiltinRet::Unknown, BF_NO_VEC},
    {"LCASE$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LCM", BuiltinRet::Unknown, BF_NO_VEC},
    {"LEFT", BuiltinRet::Unknown, BF_FRESH_STR},
    {"LEFT$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LEN", BuiltinRet::I64, BF_NO_VEC | BF_READS_ARGS},
    {"LENV", BuiltinRet::Unknown, BF_NO_VEC},
    {"LINE", BuiltinRet::Unknown, BF_NO_VEC},
    {"LINSPACE", BuiltinRet::Arr, BF_NO_VEC},
    {"LIST", BuiltinRet::Unknown, BF_NO_VEC},
    {"LIST_RECUR", BuiltinRet::Unknown, BF_NO_VEC},
    {"LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"LOCATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"LOWER$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LPAD$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"LTRIM$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"MAP.CLEAR", BuiltinRet::Unknown, BF_NO_VEC | BF_MAP_ARG1},
    {"MAP.DELETE", BuiltinRet::Unknown, BF_NO_VEC | BF_MAP_ARG1},
    {"MAP.EXISTS", BuiltinRet::Bool, BF_NO_VEC},
    {"MAP.FROM", BuiltinRet::Handle, BF_NO_VEC | BF_KEEPS_ARGS},
    {"MAP.ITEMS", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS | BF_MAP_ARG1},
    {"MAP.KEYS", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS | BF_MAP_ARG1},
    {"MAP.MERGE", BuiltinRet::Unknown, BF_NO_VEC | BF_KEEPS_ARGS},
    {"MAP.SIZE", BuiltinRet::Unknown, BF_NO_VEC | BF_MAP_ARG1},
    {"MAP.VALUES", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS | BF_MAP_ARG1},
    {"MAT4.IDENTITY", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.LOOKAT", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.MUL", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.PERSPECTIVE", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.ROTATE", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.SCALE", BuiltinRet::Handle, BF_NO_VEC},
    {"MAT4.TRANSLATE", BuiltinRet::Handle, BF_NO_VEC},
    {"MATMUL", BuiltinRet::Arr, BF_NO_VEC},
    {"MAX", BuiltinRet::F64, BF_NO_VEC},
    {"MEAN", BuiltinRet::F64, BF_NO_VEC},
    {"MEDIAN", BuiltinRet::F64, BF_NO_VEC},
    {"MID", BuiltinRet::Unknown, BF_FRESH_STR},
    {"MID$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"MIDI.SEND", BuiltinRet::Bool, BF_NONE},
    {"MIN", BuiltinRet::F64, BF_NO_VEC},
    {"MKDIR", BuiltinRet::Unknown, BF_NO_VEC},
    {"MKTEMP$", BuiltinRet::Unknown, BF_NO_VEC},
    {"MON.DEVICES", BuiltinRet::Handle, BF_NONE},
    {"MON.RECSTART", BuiltinRet::Bool, BF_NONE},
    {"MON.RUNNING", BuiltinRet::Bool, BF_NONE},
    {"MON.SCOPE", BuiltinRet::Arr, BF_NONE},
    {"MON.START", BuiltinRet::Bool, BF_NONE},
    {"MOUSEB", BuiltinRet::Bool, BF_NO_VEC},
    {"MOUSEX", BuiltinRet::Unknown, BF_NO_VEC},
    {"MOUSEY", BuiltinRet::Unknown, BF_NO_VEC},
    {"MSGBOX", BuiltinRet::Unknown, BF_NO_VEC},
    {"MUSIC.PLAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"MUSIC.STOP", BuiltinRet::Unknown, BF_NO_VEC},
    {"MVINS", BuiltinRet::Arr, BF_NO_VEC},
    {"MVLET", BuiltinRet::Arr, BF_NO_VEC},
    {"NET.ACCEPT", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.ALIVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.CONNECT", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.ERROR$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.LISTEN", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.PEER$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.PORT", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.RECV$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.RECVFROM", BuiltinRet::Handle, BF_NO_VEC},
    {"NET.RECVLINE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.SEND", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.SENDTO", BuiltinRet::Unknown, BF_NO_VEC},
    {"NET.UDP", BuiltinRet::Unknown, BF_NO_VEC},
    {"NORMALIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"NOW", BuiltinRet::Str, BF_DATE | BF_NO_VEC},
    {"NOW_EPOCH", BuiltinRet::Unknown, BF_NO_VEC},
    {"OCT$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"ONES", BuiltinRet::Arr, BF_NO_VEC},
    {"OPTION", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.ARGS", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"OS.EXEC", BuiltinRet::Handle, BF_NO_VEC},
    {"OS.FEATURE", BuiltinRet::Bool, BF_NO_VEC},
    {"OS.GETOS", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.GETOS$", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.HOSTNAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.IP$", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"OS.SCREENSHOT", BuiltinRet::Unknown, BF_NO_VEC},
    {"OUTER", BuiltinRet::Arr, BF_NO_VEC},
    {"PACK$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PACKSIZE", BuiltinRet::Unknown, BF_NO_VEC},
    {"PARTICLE.CLEAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"PARTICLE.COUNT", BuiltinRet::Unknown, BF_NO_VEC},
    {"PARTICLE.DRAW", BuiltinRet::Unknown, BF_NO_VEC},
    {"PARTICLE.EMIT", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.BASENAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.DIRNAME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.EXT$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.JOIN$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PATH.NORMALIZE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PDF.TEXT$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PI", BuiltinRet::Unknown, BF_CONST},
    {"PLACE", BuiltinRet::Arr, BF_NO_VEC},
    {"PLOTRAW", BuiltinRet::Unknown, BF_NO_VEC},
    {"POP", BuiltinRet::Unknown, BF_NO_VEC},
    {"PRINT", BuiltinRet::Unknown, BF_READS_ARGS},
    {"PRODUCT", BuiltinRet::F64, BF_NO_VEC},
    {"PSET", BuiltinRet::Unknown, BF_NO_VEC},
    {"PUSH", BuiltinRet::Unknown, BF_NO_VEC | BF_KEEPS_ARGS},
    {"PWD", BuiltinRet::Unknown, BF_NO_VEC},
    {"PY.DIR$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PY.EVAL", BuiltinRet::Handle, BF_NO_VEC},
    {"PY.GET", BuiltinRet::Handle, BF_NO_VEC},
    {"PY.HELP$", BuiltinRet::Unknown, BF_NO_VEC},
    {"PY.SET", BuiltinRet::Bool, BF_NO_VEC},
    {"PYTHON$", BuiltinRet::Unknown, BF_NO_VEC},
    {"QR", BuiltinRet::Handle, BF_NO_VEC},
    {"RANDOMSEED", BuiltinRet::Unknown, BF_NO_VEC},
    {"RANGE", BuiltinRet::Arr, BF_NO_VEC},
    {"REACT_BIND", BuiltinRet::Unknown, BF_NO_VEC},
    {"RECT", BuiltinRet::Unknown, BF_NO_VEC},
    {"RECUR", BuiltinRet::Unknown, BF_NO_VEC},
    {"REDUCE", BuiltinRet::F64, BF_NO_VEC},
    {"REGEX.FINDALL", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REGEX.MATCH", BuiltinRet::Handle, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REGEX.REPLACE", BuiltinRet::Unknown, BF_NO_VEC},
    {"REGEX_MATCH", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REGEX_REPLACE$", BuiltinRet::Unknown, BF_NO_VEC},
    {"REPEAT$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"REPLACE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"RESHAPE", BuiltinRet::Arr, BF_NO_VEC},
    {"REVERSE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"REVERSE$", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS | BF_FRESH_STR},
    {"RIGHT", BuiltinRet::Unknown, BF_FRESH_STR},
    {"RIGHT$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"RMDIR", BuiltinRet::Unknown, BF_NO_VEC},
    {"RNG.FILL", BuiltinRet::Arr, BF_NO_VEC},
    {"RNG.FREE", BuiltinRet::Unknown, BF_NO_VEC},
    {"RNG.INT", BuiltinRet::Unknown, BF_NO_VEC},
    {"RNG.NEW", BuiltinRet::Unknown, BF_NO_VEC},
    {"RNG.NEXT", BuiltinRet::Unknown, BF_NO_VEC},
    {"ROTATE", BuiltinRet::Arr, BF_NO_VEC},
    {"ROTL", BuiltinRet::Unknown, BF_NO_VEC},
    {"ROTR", BuiltinRet::Unknown, BF_NO_VEC},
    {"ROUNDED_RECT", BuiltinRet::Unknown, BF_NO_VEC},
    {"RPAD$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"RTRIM$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"SAVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SCAN", BuiltinRet::Arr, BF_NO_VEC},
    {"SCREEN", BuiltinRet::Unknown, BF_NO_VEC},
    {"SCREENFLIP", BuiltinRet::Unknown, BF_NO_VEC},
    {"SELECT", BuiltinRet::Unknown, BF_NO_VEC},
    {"SETENV", BuiltinRet::Unknown, BF_NO_VEC},
    {"SETFONT", BuiltinRet::Unknown, BF_NO_VEC},
    {"SETLOCALE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SFX.LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"SFX.PLAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SHIFT", BuiltinRet::Arr, BF_NO_VEC},
    {"SHUFFLE", BuiltinRet::Arr, BF_NO_VEC},
    {"SLEEP", BuiltinRet::Unknown, BF_NO_VEC},
    {"SLICE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"SOLVE", BuiltinRet::Arr, BF_NO_VEC},
    {"SORT", BuiltinRet::Unknown, BF_NO_VEC | BF_TAGGED_CELLS},
    {"SOUND.BITCRUSH", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.BPM", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.COMPRESSOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.DELAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.DELAYSEND", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.DISTORTION", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.EQ", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.FILTER", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.FM", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.GAIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.GET_BUS_WAVE", BuiltinRet::Arr, BF_NO_VEC},
    {"SOUND.GET_WAVE", BuiltinRet::Arr, BF_NO_VEC},
    {"SOUND.INIT", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.LFO", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.NOTE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.PAN", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.PLAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.PLAYBUFFER", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.RELEASE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.RENDER", BuiltinRet::Arr, BF_NONE},
    {"SOUND.RESET", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.REVERB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.REVERBSEND", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.RINGMOD", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.SAMPLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.SCALE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.SEQ", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.SHUTDOWN", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.SIDECHAIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.STATS", BuiltinRet::Str, BF_NONE},
    {"SOUND.STOP", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.UNISON", BuiltinRet::Unknown, BF_NO_VEC},
    {"SOUND.VOICE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPACE$", BuiltinRet::Unknown, BF_FRESH_STR},
    {"SPLIT", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"SPRITE.ALPHA", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.ANIM", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.COLLISION", BuiltinRet::Bool, BF_NO_VEC},
    {"SPRITE.COLLISIONS", BuiltinRet::Arr, BF_NO_VEC},
    {"SPRITE.COLLISION_FIRST", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.CREATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.DELETE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.DRAW", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.DRAW_ALL", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.FLIP", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.FRAME", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.GET_VX", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.GET_VY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.GET_X", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.GET_Y", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.GRAVITY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.GROUP", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.HEIGHT", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.LAND", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.LOAD", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.MOVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.ON_GROUND", BuiltinRet::Bool, BF_NO_VEC},
    {"SPRITE.PLAY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.PLAYING", BuiltinRet::Bool, BF_NO_VEC},
    {"SPRITE.POS", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.ROTATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.SAVE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.SCALE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.SETBUFFER", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.SETPIXEL", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.SET_ORIGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.STOP", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.UPDATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.VELOCITY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.VISIBLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.WIDTH", BuiltinRet::Unknown, BF_NO_VEC},
    {"SPRITE.ZORDER", BuiltinRet::Unknown, BF_NO_VEC},
    {"SQL.CLOSE", BuiltinRet::Bool, BF_NO_VEC},
    {"SQL.COLUMNS", BuiltinRet::Arr, BF_NO_VEC},
    {"SQL.ERRMSG$", BuiltinRet::Unknown, BF_NO_VEC},
    {"SQL.EXEC", BuiltinRet::Unknown, BF_NO_VEC},
    {"SQL.OPEN", BuiltinRet::Unknown, BF_NO_VEC},
    {"SQL.QUERY", BuiltinRet::Unknown, BF_NO_VEC},
    {"SQL.TABLE", BuiltinRet::Arr, BF_NO_VEC},
    {"STACK", BuiltinRet::Arr, BF_NO_VEC},
    {"STARTSWITH", BuiltinRet::Bool, BF_READS_ARGS},
    {"STDEV", BuiltinRet::F64, BF_NO_VEC},
    {"STR", BuiltinRet::Unknown, BF_FRESH_STR},
    {"STR$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"SUM", BuiltinRet::F64, BF_NO_VEC},
    {"SVD", BuiltinRet::Handle, BF_NO_VEC},
    {"SYS.CALL", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.INB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.OUTB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.PEEK", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.PEEKB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.PEEKW", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.POKE", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.POKEB", BuiltinRet::Unknown, BF_NO_VEC},
    {"SYS.POKEW", BuiltinRet::Unknown, BF_NO_VEC},
    {"TAKE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"TAKE_WHILE", BuiltinRet::Arr, BF_NO_VEC},
    {"TALLY", BuiltinRet::Arr, BF_NO_VEC},
    {"TENSOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"TEXT", BuiltinRet::Unknown, BF_NO_VEC},
    {"THREAD.GETRESULT", BuiltinRet::Handle, BF_NO_VEC},
    {"THREAD.ISDONE", BuiltinRet::Bool, BF_NO_VEC},
    {"TICK", BuiltinRet::Unknown, BF_NO_VEC},
    {"TILED.COLLIDES", BuiltinRet::Bool, BF_NONE},
    {"TILED.LAYERS$", BuiltinRet::Arr, BF_NONE},
    {"TILED.LOAD", BuiltinRet::Bool, BF_NONE},
    {"TILED.OBJECTS", BuiltinRet::Handle, BF_NONE},
    {"TILED.PROPERTIES", BuiltinRet::Handle, BF_NONE},
    {"TILED.SIZE", BuiltinRet::Arr, BF_NONE},
    {"TILED.TILE_SIZE", BuiltinRet::Arr, BF_NONE},
    {"TILEMAP.COLLIDES", BuiltinRet::Bool, BF_NO_VEC},
    {"TILEMAP.CREATE", BuiltinRet::Unknown, BF_NO_VEC},
    {"TILEMAP.DRAW", BuiltinRet::Unknown, BF_NO_VEC},
    {"TILEMAP.GET", BuiltinRet::Unknown, BF_NO_VEC},
    {"TILEMAP.SET", BuiltinRet::Unknown, BF_NO_VEC},
    {"TILEMAP.SIZE", BuiltinRet::Arr, BF_NO_VEC},
    {"TILEMAP.TILE_AT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TIME$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TOGGLE_FULLSCREEN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TRANSPOSE", BuiltinRet::Arr, BF_NO_VEC},
    {"TRIM$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"TUI.BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.BG_COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.BORDER_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.BORDER_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.BUTTON", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.CANVAS_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.CANVAS_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.CHECKBOX", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.DROPDOWN", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.EXIT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.GAUGE", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.GRID_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.GRID_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.HBOX_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.HBOX_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.HEADING", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.HEIGHT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.INPUT", BuiltinRet::Str, BF_NO_VEC},
    {"TUI.INPUT_DOUBLE", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.INPUT_INT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.KEY$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.LAST_RENDER_MS", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.LINE", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.LINK", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MENU", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.MENUBAR_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MENUBAR_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MENUITEM", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.MODAL_BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.MODAL_CLOSE", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MODAL_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MODAL_OPEN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MOUSE_BTN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MOUSE_WHEEL", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MOUSE_X", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.MOUSE_Y", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.ON", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.PARAGRAPH", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.PIXEL", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.POP_COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.PROGRESS", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.QUIT", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.RADIO", BuiltinRet::I64, BF_NO_VEC},
    {"TUI.RENDER", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.RENDER_HEADLESS$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SAME_LINE", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SELECTABLE", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.SEPARATOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SEPARATOR_TEXT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SIZE", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SLIDER", BuiltinRet::F64, BF_NO_VEC},
    {"TUI.SPACER", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SPINNER", BuiltinRet::F64, BF_NO_VEC},
    {"TUI.STYLE_POP", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.STYLE_PUSH", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.SUBMENU_BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.SUBMENU_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.TABLE_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.TABLE_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.TABLE_ROW", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.TAB_BAR_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.TAB_BAR_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.TAB_BEGIN", BuiltinRet::Bool, BF_NO_VEC},
    {"TUI.TAB_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.TEXT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.THEME", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.VBOX_BEGIN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.VBOX_END", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.VERSION$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.WAIT_EVENT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TUI.WIDTH", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.BACKWARD", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.CLEAR", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.DRAW", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.FORWARD", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.HOME", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.LEFT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.PENDOWN", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.PENUP", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.RIGHT", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.SETHEADING", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.SETPOS", BuiltinRet::Unknown, BF_NO_VEC},
    {"TURTLE.SET_COLOR", BuiltinRet::Unknown, BF_NO_VEC},
    {"TXTREADER$", BuiltinRet::Unknown, BF_NO_VEC},
    {"TXTWRITER", BuiltinRet::Unknown, BF_NO_VEC},
    {"TYPEOF", BuiltinRet::Unknown, BF_NO_VEC | BF_READS_ARGS},
    {"UCASE$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"UNIQUE", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"UNPACK", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"UNREACT", BuiltinRet::Unknown, BF_NO_VEC},
    {"UPPER$", BuiltinRet::Unknown, BF_READS_ARGS | BF_FRESH_STR},
    {"VAL", BuiltinRet::Unknown, BF_READS_ARGS},
    {"VARIANCE", BuiltinRet::F64, BF_NO_VEC},
    {"VARS", BuiltinRet::Unknown, BF_NO_VEC},
    {"VBCRLF", BuiltinRet::Unknown, BF_CONST},
    {"VBNEWLINE", BuiltinRet::Unknown, BF_CONST},
    {"VBTAB", BuiltinRet::Unknown, BF_CONST},
    {"WAITKEY$", BuiltinRet::Unknown, BF_NO_VEC},
    {"WAV.INFO", BuiltinRet::Handle, BF_NONE},
    {"WAV.READ", BuiltinRet::Handle, BF_NONE},
    {"WAV.RECORD", BuiltinRet::Handle, BF_NONE},
    {"WAV.RECSTART", BuiltinRet::Bool, BF_NONE},
    {"WAV.RECSTOP", BuiltinRet::Handle, BF_NONE},
    {"WAV.WRITE", BuiltinRet::Bool, BF_NO_VEC},
    {"XSORT", BuiltinRet::Arr, BF_NO_VEC},
    {"YIELD", BuiltinRet::Unknown, BF_NO_VEC},
    {"ZEROS", BuiltinRet::Arr, BF_NO_VEC},
    {"ZIP", BuiltinRet::Arr, BF_NO_VEC},
    {"ZIP.LIST", BuiltinRet::Arr, BF_NO_VEC | BF_TAGGED_CELLS},
    {"ZIP.READ", BuiltinRet::Handle, BF_NO_VEC},
    {"ZIP.WRITE", BuiltinRet::Unknown, BF_NO_VEC},
    {"__EVENT_ON", BuiltinRet::Unknown, BF_NO_VEC},
    {"__EVENT_RAISE", BuiltinRet::Unknown, BF_NO_VEC},
    {"__FFI_DECLARE", BuiltinRet::Unknown, BF_NO_VEC},
    {"__MAKE_UDT_ARRAY__", BuiltinRet::Unknown, BF_NO_VEC},
};

// Compares a name case-insensitively with an upper-case table name:
// negative, zero or positive like strcmp.
inline int builtin_name_cmp(std::string_view name, const char* table_name) {
    size_t i = 0;
    for (; i < name.size() && table_name[i]; i++) {
        unsigned char a = (unsigned char)name[i];
        if (a >= 'a' && a <= 'z') a = (unsigned char)(a - 'a' + 'A');
        unsigned char b = (unsigned char)table_name[i];
        if (a != b) return a < b ? -1 : 1;
    }
    if (i < name.size()) return 1;
    return table_name[i] ? -1 : 0;
}

constexpr bool builtin_sigs_sorted() {
    for (size_t i = 1; i < sizeof(kBuiltinSigs) / sizeof(kBuiltinSigs[0]); i++) {
        const char* a = kBuiltinSigs[i - 1].name;
        const char* b = kBuiltinSigs[i].name;
        size_t k = 0;
        while (a[k] && a[k] == b[k]) k++;
        if ((unsigned char)a[k] >= (unsigned char)b[k]) return false;
    }
    return true;
}
static_assert(builtin_sigs_sorted(), "kBuiltinSigs must be sorted by name, without duplicates");

// Case-insensitive; nullptr for a name the table does not list.
inline const BuiltinSig* builtin_sig(std::string_view name) {
    size_t lo = 0, hi = sizeof(kBuiltinSigs) / sizeof(kBuiltinSigs[0]);
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        int c = builtin_name_cmp(name, kBuiltinSigs[mid].name);
        if (c == 0) return &kBuiltinSigs[mid];
        if (c < 0) hi = mid; else lo = mid + 1;
    }
    return nullptr;
}

inline BuiltinRet builtin_ret(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s ? s->ret : BuiltinRet::Unknown;
}

inline bool builtin_is(std::string_view name, BuiltinRet ret) {
    return builtin_ret(name) == ret;
}

inline bool builtin_has(std::string_view name, BuiltinFlags flag) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & flag);
}

inline bool builtin_returns_date(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_DATE);
}

inline bool builtin_no_vectorize(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_NO_VEC);
}

inline bool builtin_reads_args(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_READS_ARGS);
}

inline bool builtin_fresh_string(std::string_view name) {
    const BuiltinSig* s = builtin_sig(name);
    return s && (s->flags & BF_FRESH_STR);
}
