// Auto-generated list of all native function name parts.
// Used by the editor for syntax highlighting.
// Do not edit by hand - regenerate via
//   python tools/update_syntax_highlighting.py
#pragma once
#include <string>
#include <unordered_set>

inline const std::unordered_set<std::string>& native_names() {
    static const std::unordered_set<std::string> ns = {
        "ABS", "ACOS", "AI", "ALL",
        "ALPHA", "ANIM", "ANY", "APPEND",
        "ARGMAX", "ARGS", "ASC", "ASIN",
        "ATAN", "ATAN2", "AUDIO", "AVAILABLE",
        "AVAIL_HEIGHT", "AVAIL_WIDTH", "AWAIT", "AXIS",
        "BACKWARD", "BASE64_DECODE$", "BASE64_ENCODE$", "BASENAME$",
        "BEGIN", "BEGIN_CHILD", "BEGIN_MAIN_MENU_BAR", "BEGIN_MENU",
        "BEGIN_MENU_BAR", "BEGIN_POPUP", "BEGIN_POPUP_MODAL", "BEGIN_TABLE",
        "BEGIN_TAB_BAR", "BEGIN_TAB_ITEM", "BIN$", "BINREADER$",
        "BINWRITER", "BITCRUSH", "BOUNDS", "BPM",
        "BUTTON", "BYTEAT", "CAM", "CAPTURE",
        "CBOOL", "CD", "CDATE", "CDBL",
        "CEIL", "CHAT", "CHAT_JSON", "CHAT_RAW",
        "CHAT_STREAM", "CHECKBOX", "CHR", "CHR$",
        "CINT", "CIRCLE", "CIRCLE_SECTOR", "CLAMP",
        "CLASSIFIER_ADD", "CLASSIFIER_ADD_BATCH", "CLASSIFIER_BUILD_INDEX", "CLASSIFIER_CREATE",
        "CLASSIFIER_FREE", "CLASSIFIER_INFO", "CLASSIFIER_LOAD", "CLASSIFIER_PREDICT",
        "CLASSIFIER_SAVE", "CLEAR", "CLEARHEADERS", "CLEAR_GRAMMAR",
        "CLEAR_HISTORY", "CLEAR_RECUR", "CLIPBOARD", "CLNG",
        "CLOSE", "CLOSE_CURRENT_POPUP", "CLS", "CODEC",
        "COL", "COLLAPSING_HEADER", "COLLIDES", "COLLISION",
        "COLLISIONS", "COLLISION_FIRST", "COLOR", "COLOR_TO_ALPHA",
        "COMBO", "COMPRESSOR", "CONVOLVE", "COS",
        "COSH", "COSINE_SIM", "COUNT", "CREATE",
        "CREATEOBJECT", "CROSS", "CSNG", "CSTR",
        "CSVREADER", "CSVWRITER", "CUMPROD", "CUMSUM",
        "CURSOR", "CVDATE", "DATE$", "DATEADD",
        "DATEDIFF", "DAY", "DEBUG", "DELAY",
        "DELAYSEND", "DELETE", "DETOKENIZE", "DIFF",
        "DIR", "DIR$", "DISTANCE", "DISTORTION",
        "DOT", "DRAW", "DRAWCOLOR", "DRAWIMAGE",
        "DRAWIMAGE_EX", "DRAWIMAGE_REGION", "DRAW_ALL", "DRAW_CAPTURE",
        "DRAW_LAYER", "DROP", "DUMMY", "DUMP",
        "E", "ELLIPSE", "EMBED", "EMBED_LLM",
        "EMIT", "END", "ENDSWITH", "END_CHILD",
        "END_MAIN_MENU_BAR", "END_MENU", "END_MENU_BAR", "END_POPUP",
        "END_TABLE", "END_TAB_BAR", "END_TAB_ITEM", "EQ",
        "EVAL", "EXEC", "EXECUTE", "EXISTS",
        "EXP", "EXT$", "FAC", "FADE",
        "FEATURE", "FILTER", "FINDALL", "FIND_IN_ARRAY",
        "FLAG", "FLATTEN", "FLIP", "FLOOR",
        "FLUSH", "FM", "FOLLOW", "FORMAT$",
        "FORMAT_DATE", "FORWARD", "FRAME", "FREE",
        "FREEIMAGE", "FREEMUS", "FREE_LLM", "FRMV$",
        "FROM", "GAIN", "GET", "GET$",
        "GETENV$", "GETOS", "GETOS$", "GETRESULT",
        "GETX", "GETY", "GET_ASYNC$", "GET_BUS_WAVE",
        "GET_HISTORY", "GET_VX", "GET_VY", "GET_WAVE",
        "GET_X", "GET_Y", "GFX", "GRADE",
        "GRAVITY", "GROUP", "GUI", "HAT",
        "HEIGHT", "HELP", "HELP$", "HELPMARKER",
        "HEX$", "HISTOGRAM", "HOME", "HOSTNAME$",
        "HOUR", "HSV_RGB", "HTTP", "IIF",
        "INDEXOF", "INFO", "INIT", "INKEY$",
        "INPUT", "INPUT_DOUBLE", "INPUT_INT", "INSERT$",
        "INSTR", "INSTR$", "INT", "INTEGRATE",
        "INVERT", "IOTA", "IP$", "ISARR",
        "ISBOOL", "ISDONE", "ISMAP", "ISNONE",
        "ISNULL", "ISNUM", "ISSTR", "ITEMS",
        "ITEM_DEACTIVATED_AFTER_EDIT", "ITEM_RECT", "JOIN", "JOIN$",
        "JOY", "JSON", "KEYS", "KEYSTATE",
        "KILL", "LAND", "LAYERS$", "LCASE",
        "LCASE$", "LEFT", "LEFT$", "LEN",
        "LENV", "LERP", "LFO", "LINE",
        "LINSPACE", "LIST", "LISTBOX", "LIST_RECUR",
        "LLM_INFO", "LOAD", "LOADIMAGE", "LOADMUS",
        "LOADWAV", "LOAD_EMBEDDINGS", "LOAD_LLM", "LOCATE",
        "LOG", "LOG10", "LTRIM$", "MAP",
        "MATCH", "MATMUL", "MAX", "MEAN",
        "MEDIAN", "MENU_ITEM", "MERGE", "MID",
        "MID$", "MIN", "MINUTE", "MKDIR",
        "MONTH", "MOUSEB", "MOUSEBUTTON", "MOUSEX",
        "MOUSEY", "MOVE", "MUSIC", "MVLET",
        "NAME$", "NORMALIZE", "NOTE", "NOW",
        "OBJECTS", "OCT$", "ONES", "ON_GROUND",
        "OPEN", "OPEN_POPUP", "OPTION", "OS",
        "OUTER", "PACK$", "PAN", "PARSE$",
        "PARTICLE", "PATH", "PAUSE", "PAUSEMUS",
        "PENDOWN", "PENUP", "PI", "PLACE",
        "PLAY", "PLAYING", "PLAYMUS", "PLOTRAW",
        "PLOT_HISTOGRAM", "PLOT_LINES", "PLOT_POINTS", "PLOT_POINTS_TEX",
        "POLLEVENT", "POP", "POP_ID", "POP_STYLE_COLOR",
        "POS", "POST$", "POST_ASYNC$", "PRODUCT",
        "PROGRESS", "PROPERTIES", "PSET", "PUSH",
        "PUSH_ID", "PUSH_STYLE_COLOR", "PUT$", "PUT_ASYNC$",
        "PWD", "RADIO", "RAG_ADD", "RAG_ADD_DIR",
        "RAG_ADD_FILE", "RAG_BUILD_INDEX", "RAG_CLEAR", "RAG_CREATE",
        "RAG_FREE", "RAG_INFO", "RAG_LOAD", "RAG_QUERY",
        "RAG_QUERY_FULL", "RAG_QUERY_STREAM", "RAG_SAVE", "RAG_SEARCH",
        "RANDOM", "RANDOMSEED", "RANGE", "REACT_BIND",
        "READ$", "RECT", "RECUR", "REDUCE",
        "REGEX", "REGEX_MATCH", "REGEX_REPLACE$", "RELEASE",
        "RELEASEALL", "RELEASEOBJECT", "REPLACE", "REPLACE$",
        "RESET", "RESHAPE", "RESUME", "RESUMEMUS",
        "REVERB", "REVERBSEND", "REVERSE", "REVERSE$",
        "RIGHT", "RIGHT$", "RINGMOD", "RND",
        "ROTATE", "ROUND", "ROUNDED_RECT", "RTRIM$",
        "RUN", "SAME_LINE", "SAMPLE", "SAVE",
        "SAVE_IMAGE", "SAVE_SCREENSHOT", "SCALE", "SCAN",
        "SCREEN", "SCREENFLIP", "SCREENHEIGHT", "SCREENWIDTH",
        "SECOND", "SELECT", "SELECTABLE", "SEPARATOR",
        "SEPARATOR_TEXT", "SEQ", "SERIAL", "SERVER",
        "SET", "SETFONT", "SETHEADER", "SETHEADING",
        "SETLOCALE", "SETPOS", "SET_COLOR", "SET_CURSOR_SCREEN_POS",
        "SET_GRAMMAR", "SET_JSON_MODE", "SET_KEYBOARD_FOCUS", "SET_NEXT_ITEM_WIDTH",
        "SET_ORIGIN", "SFX", "SGN", "SHA256$",
        "SHAKE", "SHIFT", "SHL", "SHOW_FONT_ATLAS",
        "SHR", "SHUFFLE", "SHUTDOWN", "SIDECHAIN",
        "SIMILARITY", "SIN", "SINH", "SIZE",
        "SLEEP", "SLICE", "SLIDER", "SOFTMAX",
        "SOLVE", "SOUND", "SPACE$", "SPLIT",
        "SPRITE", "SQR", "STACK", "STARTSWITH",
        "STATS", "STATUSCODE", "STDEV", "STOP",
        "STOPMUS", "STR", "STR$", "STRINGIFY$",
        "SUM", "TABLE_HEADERS_ROW", "TABLE_NEXT_COLUMN", "TABLE_NEXT_ROW",
        "TABLE_SETUP_COLUMN", "TABLE_SET_COLUMN_INDEX", "TAKE", "TAN",
        "TANH", "TENSOR", "TEXT", "TEXTSIZE",
        "TEXT_WRAPPED", "THEME", "THREAD", "TICK",
        "TICKS", "TILED", "TILEMAP", "TILE_AT",
        "TILE_SIZE", "TIME$", "TOGGLE_FULLSCREEN", "TOKENIZE",
        "TOKEN_COUNT", "TONUM", "TOOLTIP", "TOOL_ADD",
        "TOOL_CHAT", "TOOL_LIST", "TOOL_REMOVE", "TOPK",
        "TOSTR", "TRANSPOSE", "TREE_NODE", "TREE_POP",
        "TRIM", "TRIM$", "TROFF", "TRON",
        "TRUNC", "TURTLE", "TXTREADER$", "TXTWRITER",
        "TYPEOF", "UCASE", "UCASE$", "UNIQUE",
        "UNISON", "UNPACK", "UNREACT", "UPDATE",
        "UUID$", "VAL", "VALUES", "VARIANCE",
        "VARS", "VBCRLF", "VBNEWLINE", "VBTAB",
        "VELOCITY", "VISIBLE", "VOICE", "VOLUME",
        "VOLUMEMUS", "WAITKEY$", "WEEKDAY", "WIDTH",
        "WINDOW_HEIGHT", "WINDOW_WIDTH", "WRITE", "X",
        "XSORT", "Y", "YEAR", "ZEROS",
        "ZIP", "ZORDER"
    };
    return ns;
}
